"""
接口模板模型
Generated by scaffold script
"""
from sqlalchemy import Boolean, Column, BigInteger, String, Text, SmallInteger, Integer, DateTime
from core.db import Base


class ApiTemplate(Base):
    """接口模板表模型"""
    
    __tablename__ = 'api_template'
    
    template_id = Column(BigInteger, primary_key=True, autoincrement=True, comment="主键")
    field_name = Column(String(50), comment="字段名称")
    field_type = Column(SmallInteger, comment="字段类型")
    field_size = Column(Integer, comment="字段大小")
    is_required = Column(String(10), comment="非空")
    is_unique = Column(Boolean, comment="唯一")
    api_id = Column(BigInteger, comment="接口id")
    remark = Column(Text, comment="备注")
    creator = Column(String(50), comment="创建人")
    create_time = Column(DateTime, comment="创建时间")
    update_time = Column(DateTime, comment="更新时间")

    def __repr__(self):
        return f"<ApiTemplate(template_id={self.template_id})>"
