"""
接口信息模型
Generated by scaffold script
"""
from sqlalchemy import Column, BigInteger, String, Text, SmallInteger, Integer, DateTime
from core.db import Base


class ApiInfo(Base):
    """接口信息表模型"""
    
    __tablename__ = 'api_info'
    
    api_id = Column(BigInteger, primary_key=True, autoincrement=True, comment="主键")
    api_name = Column(String(50), comment="接口名称")
    method_type = Column(SmallInteger, comment="方法类型")
    method_url = Column(String(500), comment="方法URL")
    project_id = Column(BigInteger, comment="项目id")
    token_id = Column(BigInteger, comment="tokenId")
    request_header = Column(String(500), comment="请求头")
    params_path = Column(String(50), comment="参数位置")
    description = Column(Text, comment="描述")
    remark = Column(Text, comment="备注")
    creator = Column(String(50), comment="创建人")
    create_time = Column(DateTime, comment="创建时间")
    update_time = Column(DateTime, comment="更新时间")

    def __repr__(self):
        return f"<ApiInfo(api_id={self.api_id})>"
