"""
参数实例模型
Generated by scaffold script
"""
from sqlalchemy import Column, BigInteger, String, Text, SmallInteger, Integer, DateTime
from core.db import Base


class ApiInstance(Base):
    """参数实例表模型"""
    
    __tablename__ = 'api_instance'
    
    instance_id = Column(BigInteger, primary_key=True, autoincrement=True, comment="主键")
    instance_name = Column(String(50), comment="接口实例名称")
    description = Column(Text, comment="描述")
    api_id = Column(BigInteger, comment="接口id")
    instance_json = Column(Text, comment="实例JSON")
    exec_count = Column(Integer, comment="执行次数")
    status = Column(SmallInteger, comment="状态")
    expect_result = Column(Text, comment="期望结果")
    remark = Column(Text, comment="备注")
    creator = Column(String(50), comment="创建人")
    create_time = Column(DateTime, comment="创建时间")
    update_time = Column(DateTime, comment="更新时间")

    def __repr__(self):
        return f"<ApiInstance(instance_id={self.instance_id})>"
