"""
字典信息模型
Generated by scaffold script
"""
from sqlalchemy import Column, BigInteger, String, Text, SmallInteger, Integer, DateTime
from core.db import Base


class DictInfo(Base):
    """字典信息表模型"""
    
    __tablename__ = 'dict_info'
    
    dict_id = Column(BigInteger, primary_key=True, autoincrement=True, comment="主键")
    dict_name = Column(String(50), comment="字典名称")
    dict_key = Column(String(50), comment="键值")
    dict_value = Column(Text, comment="值")
    type = Column(SmallInteger, comment="类型")
    status = Column(SmallInteger, comment="状态")
    creator = Column(String(50), comment="创建人")
    create_time = Column(DateTime, comment="创建时间")
    update_time = Column(DateTime, comment="更新时间")

    def __repr__(self):
        return f"<DictInfo(dict_id={self.dict_id})>"
