"""
元素模板模型
Generated by scaffold script
"""
from sqlalchemy import Column, BigInteger, String, Text, SmallInteger, Integer, DateTime
from core.db import Base


class ElementTemplate(Base):
    """元素模板表模型"""
    
    __tablename__ = 'element_template'
    
    element_id = Column(BigInteger, primary_key=True, autoincrement=True, comment="主键")
    element_name = Column(String(50), comment="元素名称")
    page_id = Column(BigInteger, comment="页面id")
    locator_type = Column(SmallInteger, comment="定位器")
    element_value = Column(Text, comment="元素")
    element_type = Column(SmallInteger, comment="类型")
    status = Column(SmallInteger, comment="状态")
    operation = Column(SmallInteger, comment="操作")
    remark = Column(Text, comment="备注")
    creator = Column(String(50), comment="创建人")
    create_time = Column(DateTime, comment="创建时间")
    update_time = Column(DateTime, comment="更新时间")

    def __repr__(self):
        return f"<ElementTemplate(element_id={self.element_id})>"
