"""
流程信息模型
Generated by scaffold script
"""
from sqlalchemy import Column, BigInteger, String, Text, SmallInteger, Integer, DateTime
from core.db import Base


class FlowInfo(Base):
    """流程信息表模型"""
    
    __tablename__ = 'flow_info'
    
    flow_id = Column(BigInteger, primary_key=True, autoincrement=True, comment="主键")
    flow_name = Column(String(50), comment="流程名称")
    description = Column(Text, comment="描述")
    flow_type = Column(SmallInteger, comment="流程类型")
    project_id = Column(BigInteger, comment="项目id")
    expect_result = Column(Text, comment="预期结果")
    actual_result = Column(Text, comment="实际结果")
    status = Column(SmallInteger, comment="状态")
    remark = Column(Text, comment="备注")
    creator = Column(String(50), comment="创建人")
    create_time = Column(DateTime, comment="创建时间")
    update_time = Column(DateTime, comment="更新时间")

    def __repr__(self):
        return f"<FlowInfo(flow_id={self.flow_id})>"
