"""
流程步骤模型
Generated by scaffold script
"""
from sqlalchemy import Column, BigInteger, String, Text, SmallInteger, Integer, DateTime
from core.db import Base


class FlowStep(Base):
    """流程步骤表模型"""
    
    __tablename__ = 'flow_step'
    
    step_id = Column(BigInteger, primary_key=True, autoincrement=True, comment="主键")
    api_id = Column(BigInteger, comment="接口id")
    instance_id = Column(BigInteger, comment="实例id")
    params = Column(Text, comment="参数")
    is_batch = Column(String(10), comment="是否批处理")
    status = Column(SmallInteger, comment="状态")
    expect_result = Column(Text, comment="预期结果")
    remark = Column(Text, comment="备注")
    creator = Column(String(50), comment="创建人")
    create_time = Column(DateTime, comment="创建时间")
    update_time = Column(DateTime, comment="更新时间")

    def __repr__(self):
        return f"<FlowStep(step_id={self.step_id})>"
