"""
页面实例模型
Generated by scaffold script
"""
from sqlalchemy import Column, BigInteger, String, Text, SmallInteger, Integer, DateTime
from core.db import Base


class PageInstance(Base):
    """页面实例表模型"""
    
    __tablename__ = 'page_instance'
    
    page_instance_id = Column(BigInteger, primary_key=True, autoincrement=True, comment="主键")
    page_id = Column(BigInteger, comment="页面id")
    operation_json = Column(Text, comment="操作JSON")
    instance_name = Column(String(50), comment="页面实例名称")
    screen_photo_file = Column(String(100), comment="页面实例截图文件路径")
    description = Column(Text, comment="描述")
    expect_result = Column(Text, comment="预期结果")
    status = Column(SmallInteger, comment="状态")
    remark = Column(Text, comment="备注")
    creator = Column(String(50), comment="创建人")
    create_time = Column(DateTime, comment="创建时间")
    update_time = Column(DateTime, comment="更新时间")

    def __repr__(self):
        return f"<PageInstance(page_instance_id={self.page_instance_id})>"
