"""
页面信息模型
Generated by scaffold script
"""
from sqlalchemy import Column, BigInteger, String, Text, SmallInteger, Integer, DateTime
from core.db import Base


class PageInfo(Base):
    """页面信息表模型"""
    
    __tablename__ = 'page_info'
    
    page_id = Column(BigInteger, primary_key=True, autoincrement=True, comment="主键")
    page_name = Column(String(50), comment="页面名称")
    description = Column(Text, comment="描述")
    project_id = Column(BigInteger, comment="项目id")
    page_url = Column(String(500), comment="URL")
    token_id = Column(BigInteger, comment="tokenId")
    file_name = Column(String(50), comment="功能代码文件名称")
    function = Column(Text, comment="功能")
    remark = Column(Text, comment="备注")
    creator = Column(String(50), comment="创建人")
    create_time = Column(DateTime, comment="创建时间")
    update_time = Column(DateTime, comment="更新时间")

    def __repr__(self):
        return f"<PageInfo(page_id={self.page_id})>"
