"""
项目信息模型
Generated by scaffold script
"""
from sqlalchemy import Column, BigInteger, String, Text, SmallInteger, Integer, DateTime
from core.db import Base


class ProjectInfo(Base):
    """项目信息表模型"""
    
    __tablename__ = 'project_info'
    
    project_id = Column(BigInteger, primary_key=True, autoincrement=True, comment="主键")
    project_name = Column(String(50), comment="项目名称")
    project_address = Column(String(50), comment="项目地址")
    project_swagger = Column(String(50), comment="项目端口")
    project_env = Column(String(50), comment="项目环境")
    version = Column(String(50), comment="项目版本")
    remark = Column(Text, comment="备注")
    status = Column(SmallInteger, comment="状态")
    creator = Column(String(50), comment="创建人")
    create_time = Column(DateTime, comment="创建时间")
    update_time = Column(DateTime, comment="更新时间")

    def __repr__(self):
        return f"<ProjectInfo(project_id={self.project_id})>"
