"""
系统用户模型
Generated by scaffold script
"""
from sqlalchemy import Column, BigInteger, String, Text, SmallInteger, Integer, DateTime
from core.db import Base


class SysUser(Base):
    """系统用户表模型"""
    
    __tablename__ = 'sys_user'
    
    user_id = Column(BigInteger, primary_key=True, autoincrement=True, comment="用户id")
    nickname = Column(String(50), comment="用户昵称")
    username = Column(String(50), nullable=False, comment="用户名")
    password = Column(String(100), nullable=False, comment="密码")
    dept_id = Column(BigInteger, comment="部门id")
    status = Column(SmallInteger, comment="状态")
    remark = Column(Text, comment="备注")
    creator = Column(String(50), comment="创建人")
    create_time = Column(DateTime, comment="创建时间")
    update_time = Column(DateTime, comment="更新时间")

    def __repr__(self):
        return f"<SysUser(user_id={self.user_id})>"
