"""
Token信息模型
Generated by scaffold script
"""
from sqlalchemy import Column, BigInteger, String, Text, SmallInteger, Integer, DateTime
from core.db import Base


class TokenInfo(Base):
    """Token信息表模型"""
    
    __tablename__ = 'token_info'
    
    token_id = Column(BigInteger, primary_key=True, autoincrement=True, comment="tokenId")
    name = Column(String(50), comment="名称")
    type = Column(SmallInteger, comment="类型")
    token_type = Column(SmallInteger, comment="token类型 1api 2web")
    project_id = Column(BigInteger, comment="项目id")
    instance_id = Column(BigInteger, comment="实例id")
    status = Column(SmallInteger, comment="状态")
    token = Column(Text, comment="token")
    remark = Column(Text, comment="备注")
    creator = Column(String(50), comment="创建人")
    create_time = Column(DateTime, comment="创建时间")
    update_time = Column(DateTime, comment="更新时间")

    def __repr__(self):
        return f"<TokenInfo(token_id={self.token_id})>"
