"""
参数实例Schema
Generated by scaffold script
"""
from pydantic import BaseModel, ConfigDict, Field, field_serializer
from pydantic.alias_generators import to_camel
from typing import Optional
from datetime import datetime
from models.api_instance_model import ApiInstance



class ApiInstanceBase(BaseModel):
    """参数实例基础Schema"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True
    )
    
    instance_name: Optional[str] = Field(None, description="接口实例名称")
    description: Optional[str] = Field(None, description="描述")
    api_id: Optional[int] = Field(None, description="接口id")
    instance_json: Optional[str] = Field(None, description="实例JSON")
    exec_count: Optional[int] = Field(None, description="执行次数")
    status: Optional[int] = Field(None, description="状态")
    expect_result: Optional[str] = Field(None, description="期望结果")
    remark: Optional[str] = Field(None, description="备注")


class ApiInstanceList(ApiInstanceBase):
    """参数实例列表Schema"""
    page_num: int = Field(1, description="页码")
    page_size: int = Field(10, description="每页大小")
    def filter_params(self):
        filter_params = []
        if self.instance_name is not None:
            filter_params.append(ApiInstance.instance_name.contains(self.instance_name))
        if self.description is not None:
            filter_params.append(ApiInstance.description.contains(self.description))
        if self.api_id is not None:
            filter_params.append(ApiInstance.api_id == self.api_id)
        return filter_params

class ApiInstanceCreate(ApiInstanceBase):
    """参数实例创建Schema"""
    pass


class ApiInstanceUpdate(ApiInstanceBase):
    """参数实例更新Schema"""
    instance_id: int = Field(..., description="主键")


class ApiInstanceInfo(ApiInstanceBase):
    """参数实例响应Schema"""
    instance_id: Optional[int] = Field(None, description="主键")
    creator: Optional[str] = Field(None, description="创建人")
    create_time: Optional[datetime] = Field(None, description="创建时间")
    update_time: Optional[datetime] = Field(None, description="更新时间")
    project_id: Optional[int] = Field(None, description="项目id")
    project_name: Optional[str] = Field(None, description="项目名称")
    project_address: Optional[str] = Field(None, description="项目地址")
    api_name: Optional[str] = Field(None, description="接口名称")
    method_url: Optional[str] = Field(None, description="接口URL")

    @field_serializer('create_time', 'update_time')
    def serialize_datetime(self, dt: Optional[datetime], _info) -> Optional[str]:
        """时间字段自动转换为字符串格式"""
        if dt is None:
            return None
        return dt.strftime('%Y-%m-%d %H:%M:%S')
