"""
API执行Schemas
Generated by scaffold script
"""
from pydantic import BaseModel, ConfigDict, Field
from pydantic.alias_generators import to_camel
from typing import Optional, List


class ApiExecuteRequest(BaseModel):
    """API执行请求（通用）"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True
    )
    
    execution_type: int = Field(..., description="执行类型: 1-单实例, 2-批量实例, 3-API下所有实例, 4-项目下所有实例")
    target_id: Optional[int] = Field(None, description="目标ID (instance_id/api_id/project_id)")
    target_ids: Optional[List[int]] = Field(None, description="目标ID列表 (用于批量执行)")


class ApiExecuteResult(BaseModel):
    """API执行结果"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True
    )
    
    instance_id: int = Field(..., description="实例ID")
    success: bool = Field(..., description="是否成功")
    status_code: Optional[int] = Field(None, description="HTTP状态码")
    response_data: Optional[str] = Field(None, description="响应数据")
    error_message: Optional[str] = Field(None, description="错误信息")
    execution_time: Optional[float] = Field(None, description="执行时间(秒)")


class BatchApiExecuteResult(BaseModel):
    """批量API执行结果"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True
    )
    
    total: int = Field(..., description="总数")
    success_count: int = Field(..., description="成功数量")
    failed_count: int = Field(..., description="失败数量")
    results: List[ApiExecuteResult] = Field(..., description="执行结果列表")
