"""
接口信息Schema
Generated by scaffold script
"""
from pydantic import BaseModel, ConfigDict, Field, field_serializer
from pydantic.alias_generators import to_camel
from typing import Optional
from datetime import datetime
from models.api_info_model import ApiInfo


class ApiInfoBase(BaseModel):
    """接口信息基础Schema"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True
    )
    
    api_name: Optional[str] = Field(None, description="接口名称")
    method_type: Optional[int] = Field(None, description="方法类型")
    method_url: Optional[str] = Field(None, description="方法URL")
    project_id: Optional[int] = Field(None, description="项目id")
    token_id: Optional[int] = Field(None, description="tokenId")
    request_header: Optional[str] = Field(None, description="请求头")
    params_path: Optional[str] = Field(None, description="参数位置")
    description: Optional[str] = Field(None, description="描述")
    remark: Optional[str] = Field(None, description="备注")

class ApiInfoList(ApiInfoBase):
    page_num: int = Field(1, description="页码")
    page_size: int = Field(10, description="每页大小")
    def filter_params(self):
        filter_params = []
        if self.api_name is not None:
            filter_params.append(ApiInfo.api_name.contains(self.api_name))
        if self.method_type is not None:
            filter_params.append(ApiInfo.method_type == self.method_type)
        if self.method_url is not None:
            filter_params.append(ApiInfo.method_url.contains(self.method_url))
        if self.project_id is not None:
            filter_params.append(ApiInfo.project_id == self.project_id)
        if self.token_id is not None:
            filter_params.append(ApiInfo.token_id == self.token_id)
        return filter_params

class ApiInfoCreate(ApiInfoBase):
    """接口信息创建Schema"""
    pass


class ApiInfoUpdate(ApiInfoBase):
    api_id: int = Field(..., description="主键")


class ApiInfoInfo(ApiInfoBase):
    """接口信息响应Schema"""
    api_id: Optional[int] = Field(None, description="主键")
    project_name: Optional[str] = Field(None, description="项目名称")
    project_address: Optional[str] = Field(None, description="项目地址")
    token_name: Optional[str] = Field(None, description="Token名称")
    token: Optional[str] = Field(None, description="Token值")
    creator: Optional[str] = Field(None, description="创建人")
    create_time: Optional[datetime] = Field(None, description="创建时间")
    update_time: Optional[datetime] = Field(None, description="更新时间")

    @field_serializer('create_time', 'update_time')
    def serialize_datetime(self, dt: Optional[datetime], _info) -> Optional[str]:
        """时间字段自动转换为字符串格式"""
        if dt is None:
            return None
        return dt.strftime('%Y-%m-%d %H:%M:%S')

class BatchDeleteRequest(BaseModel):
    ids: list[int] = Field(..., description="主键列表")
    