"""
接口模板Schema
Generated by scaffold script
"""
from pydantic import BaseModel, ConfigDict, Field, field_serializer
from pydantic.alias_generators import to_camel
from typing import Optional
from datetime import datetime
from models.api_template_model import ApiTemplate
from models.api_info_model import ApiInfo



class ApiTemplateBase(BaseModel):
    """接口模板基础Schema"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True
    )
    
    field_name: Optional[str] = Field(None, description="字段名称")
    field_type: Optional[int] = Field(None, description="字段类型")
    field_size: Optional[int] = Field(None, description="字段大小")
    default_value: Optional[str] = Field(None, description="默认值")
    is_unique: Optional[str] = Field(None, description="唯一")
    is_required: Optional[str] = Field(None, description="非空")
    api_id: Optional[int] = Field(None, description="接口id")
    remark: Optional[str] = Field(None, description="备注")


class ApiTemplateList(ApiTemplateBase):
    """接口模板分页列表Schema"""
    page_num: int = Field(1, description="页码")
    page_size: int = Field(10, description="每页数量")
    template_id: Optional[int] = Field(None, description="主键")
    api_name: Optional[str] = Field(None, description="接口名称")
    project_id: Optional[int] = Field(None, description="项目ID")
    creator: Optional[str] = Field(None, description="创建人")
    def filter_params(self):
        filter_params = []
        if self.template_id is not None:
            filter_params.append(ApiTemplate.template_id == self.template_id)
        if self.api_name is not None:
            filter_params.append(ApiInfo.api_name.contains(self.api_name))
        if self.project_id is not None:
            filter_params.append(ApiInfo.project_id == self.project_id)
        if self.api_id is not None:
            filter_params.append(ApiTemplate.api_id == self.api_id)
        if self.creator is not None:
            filter_params.append(ApiTemplate.creator.contains(self.creator))
        if self.field_name is not None:
            filter_params.append(ApiTemplate.field_name.contains(self.field_name))
        if self.field_type is not None:
            filter_params.append(ApiTemplate.field_type == self.field_type)
        if self.is_required is not None:
            filter_params.append(ApiTemplate.is_required == self.is_required)
        return filter_params


class ApiTemplateCreate(ApiTemplateBase):
    """接口模板创建Schema"""
    pass


class ApiTemplateUpdate(ApiTemplateBase):
    """接口模板更新Schema"""
    template_id: int = Field(..., description="主键")


class ApiTemplateJsonParse(BaseModel):
    """JSON解析生成参数模板Schema"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True
    )

    api_id: int = Field(..., description="接口ID")
    json_text: str = Field(..., description="JSON内容")


class ApiTemplateBatchDelete(BaseModel):
    """参数模板批量删除Schema"""
    ids: list[int] = Field(..., description="主键列表")


class ApiTemplateInfo(ApiTemplateBase):
    """接口模板响应Schema"""
    template_id: Optional[int] = Field(None, description="主键")
    api_name: Optional[str] = Field(None, description="接口名称")
    project_id: Optional[int] = Field(None, description="项目ID")
    project_name: Optional[str] = Field(None, description="项目名称")
    creator: Optional[str] = Field(None, description="创建人")
    create_time: Optional[datetime] = Field(None, description="创建时间")
    update_time: Optional[datetime] = Field(None, description="更新时间")

    @field_serializer('create_time', 'update_time')
    def serialize_datetime(self, dt: Optional[datetime], _info) -> Optional[str]:
        """时间字段自动转换为字符串格式"""
        if dt is None:
            return None
        return dt.strftime('%Y-%m-%d %H:%M:%S')
