"""
字典信息Schema
Generated by scaffold script
"""
from pydantic import BaseModel, ConfigDict, Field, field_serializer
from pydantic.alias_generators import to_camel
from typing import Optional
from datetime import datetime


class DictInfoBase(BaseModel):
    """字典信息基础Schema"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True
    )
    
    dict_name: Optional[str] = Field(None, description="字典名称")
    dict_key: Optional[str] = Field(None, description="键值")
    dict_value: Optional[str] = Field(None, description="值")
    type: Optional[int] = Field(None, description="类型")
    status: Optional[int] = Field(None, description="状态")


class DictInfoCreate(DictInfoBase):
    """字典信息创建Schema"""
    pass


class DictInfoUpdate(DictInfoBase):
    """字典信息更新Schema"""
    pass


class DictInfoInfo(DictInfoBase):
    """字典信息响应Schema"""
    dict_id: Optional[int] = Field(None, description="主键")
    creator: Optional[str] = Field(None, description="创建人")
    create_time: Optional[datetime] = Field(None, description="创建时间")
    update_time: Optional[datetime] = Field(None, description="更新时间")

    @field_serializer('create_time', 'update_time')
    def serialize_datetime(self, dt: Optional[datetime], _info) -> Optional[str]:
        """时间字段自动转换为字符串格式"""
        if dt is None:
            return None
        return dt.strftime('%Y-%m-%d %H:%M:%S')
