"""
元素模板Schema
Generated by scaffold script
"""
from pydantic import BaseModel, ConfigDict, Field, field_serializer
from pydantic.alias_generators import to_camel
from typing import Optional
from datetime import datetime


class ElementTemplateBase(BaseModel):
    """元素模板基础Schema"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True
    )
    
    element_name: Optional[str] = Field(None, description="元素名称")
    page_id: Optional[int] = Field(None, description="页面id")
    locator_type: Optional[int] = Field(None, description="定位器")
    element_value: Optional[str] = Field(None, description="元素")
    element_type: Optional[int] = Field(None, description="类型")
    status: Optional[int] = Field(None, description="状态")
    operation: Optional[int] = Field(None, description="操作")
    remark: Optional[str] = Field(None, description="备注")


class ElementTemplateCreate(ElementTemplateBase):
    """元素模板创建Schema"""
    pass


class ElementTemplateUpdate(ElementTemplateBase):
    """元素模板更新Schema"""
    pass


class ElementTemplateInfo(ElementTemplateBase):
    """元素模板响应Schema"""
    element_id: Optional[int] = Field(None, description="主键")
    creator: Optional[str] = Field(None, description="创建人")
    create_time: Optional[datetime] = Field(None, description="创建时间")
    update_time: Optional[datetime] = Field(None, description="更新时间")

    @field_serializer('create_time', 'update_time')
    def serialize_datetime(self, dt: Optional[datetime], _info) -> Optional[str]:
        """时间字段自动转换为字符串格式"""
        if dt is None:
            return None
        return dt.strftime('%Y-%m-%d %H:%M:%S')
