"""
流程步骤Schema
Generated by scaffold script
"""
from pydantic import BaseModel, ConfigDict, Field, field_serializer
from pydantic.alias_generators import to_camel
from typing import Optional
from datetime import datetime


class FlowStepBase(BaseModel):
    """流程步骤基础Schema"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True
    )
    
    flow_id: Optional[int] = Field(None, description="流程ID")
    api_id: Optional[int] = Field(None, description="接口id")
    instance_id: Optional[int] = Field(None, description="实例id")
    params: Optional[str] = Field(None, description="参数(instanceJson)")
    flow_type: Optional[int] = Field(1, description="流程类型，1为API流程")
    is_batch: Optional[str] = Field(None, description="是否批处理")
    status: Optional[int] = Field(None, description="状态")
    expect_result: Optional[str] = Field(None, description="预期结果")
    remark: Optional[str] = Field(None, description="备注")


class FlowStepCreate(FlowStepBase):
    """流程步骤创建Schema"""
    pass


class FlowStepUpdate(FlowStepBase):
    """流程步骤更新Schema"""
    step_id: int = Field(..., description="主键")


class FlowStepList(BaseModel):
    """流程步骤查询Schema"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True
    )
    
    page_num: int = Field(default=1, ge=1, description="页码")
    page_size: int = Field(default=10, ge=1, le=1000, description="每页大小")
    flow_id: Optional[int] = Field(None, description="流程ID")
    api_id: Optional[int] = Field(None, description="API ID")


class FlowStepInfo(FlowStepBase):
    """流程步骤响应Schema"""
    step_id: Optional[int] = Field(None, description="主键")
    creator: Optional[str] = Field(None, description="创建人")
    create_time: Optional[datetime] = Field(None, description="创建时间")
    update_time: Optional[datetime] = Field(None, description="更新时间")
    api_name: Optional[str] = Field(None, description="API名称")
    method_url: Optional[str] = Field(None, description="API URL")
    instance_name: Optional[str] = Field(None, description="实例名称")

    @field_serializer('create_time', 'update_time')
    def serialize_datetime(self, dt: Optional[datetime], _info) -> Optional[str]:
        """时间字段自动转换为字符串格式"""
        if dt is None:
            return None
        return dt.strftime('%Y-%m-%d %H:%M:%S')
