"""
流程信息Schema
Generated by scaffold script
"""
from pydantic import BaseModel, ConfigDict, Field, field_serializer
from pydantic.alias_generators import to_camel
from typing import Optional
from datetime import datetime


class FlowInfoBase(BaseModel):
    """流程信息基础Schema"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True
    )
    
    flow_name: Optional[str] = Field(None, description="流程名称")
    description: Optional[str] = Field(None, description="描述")
    flow_type: Optional[int] = Field(1, description="流程类型，1为API流程")
    project_id: Optional[int] = Field(None, description="项目id")
    expect_result: Optional[str] = Field(None, description="预期结果")
    actual_result: Optional[str] = Field(None, description="实际结果")
    status: Optional[int] = Field(None, description="状态")
    remark: Optional[str] = Field(None, description="备注")


class FlowInfoCreate(FlowInfoBase):
    """流程信息创建Schema"""
    pass


class FlowInfoUpdate(FlowInfoBase):
    """流程信息更新Schema"""
    flow_id: int = Field(..., description="主键")


class FlowInfoList(BaseModel):
    """流程信息查询Schema"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True
    )
    
    page_num: int = Field(default=1, ge=1, description="页码")
    page_size: int = Field(default=10, ge=1, le=1000, description="每页大小")
    flow_name: Optional[str] = Field(None, description="流程名称（模糊搜索）")
    project_id: Optional[int] = Field(None, description="项目ID")
    flow_type: Optional[int] = Field(None, description="流程类型")


class FlowInfoInfo(FlowInfoBase):
    """流程信息响应Schema"""
    flow_id: Optional[int] = Field(None, description="主键")
    creator: Optional[str] = Field(None, description="创建人")
    create_time: Optional[datetime] = Field(None, description="创建时间")
    update_time: Optional[datetime] = Field(None, description="更新时间")
    project_name: Optional[str] = Field(None, description="项目名称")
    project_address: Optional[str] = Field(None, description="项目地址")

    @field_serializer('create_time', 'update_time')
    def serialize_datetime(self, dt: Optional[datetime], _info) -> Optional[str]:
        """时间字段自动转换为字符串格式"""
        if dt is None:
            return None
        return dt.strftime('%Y-%m-%d %H:%M:%S')
    
class FowInfoIds(BaseModel):
    """流程信息ID列表"""
    ids: list[int] = Field(..., description="流程ID列表")
