"""
页面实例Schema
Generated by scaffold script
"""
from pydantic import BaseModel, ConfigDict, Field, field_serializer
from pydantic.alias_generators import to_camel
from typing import Optional
from datetime import datetime


class PageInstanceBase(BaseModel):
    """页面实例基础Schema"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True
    )
    
    page_id: Optional[int] = Field(None, description="页面id")
    operation_json: Optional[str] = Field(None, description="操作JSON")
    instance_name: Optional[str] = Field(None, description="页面实例名称")
    screen_photo_file: Optional[str] = Field(None, description="页面实例截图文件路径")
    description: Optional[str] = Field(None, description="描述")
    expect_result: Optional[str] = Field(None, description="预期结果")
    status: Optional[int] = Field(None, description="状态")
    remark: Optional[str] = Field(None, description="备注")


class PageInstanceCreate(PageInstanceBase):
    """页面实例创建Schema"""
    pass


class PageInstanceUpdate(PageInstanceBase):
    """页面实例更新Schema"""
    page_instance_id: int = Field(..., description="主键")
    

class PageInstanceIds(BaseModel):
    ids: list[int] = Field(..., description="页面实例ID列表")


class PageInstanceInfo(PageInstanceBase):
    """页面实例响应Schema"""
    page_instance_id: Optional[int] = Field(None, description="主键")
    creator: Optional[str] = Field(None, description="创建人")
    create_time: Optional[datetime] = Field(None, description="创建时间")
    update_time: Optional[datetime] = Field(None, description="更新时间")

    @field_serializer('create_time', 'update_time')
    def serialize_datetime(self, dt: Optional[datetime], _info) -> Optional[str]:
        """时间字段自动转换为字符串格式"""
        if dt is None:
            return None
        return dt.strftime('%Y-%m-%d %H:%M:%S')
