"""
页面信息Schema
Generated by scaffold script
"""
from pydantic import BaseModel, ConfigDict, Field, field_serializer
from pydantic.alias_generators import to_camel
from typing import Optional
from datetime import datetime


class PageInfoBase(BaseModel):
    """页面信息基础Schema"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True
    )
    
    page_name: Optional[str] = Field(None, description="页面名称")
    description: Optional[str] = Field(None, description="描述")
    project_id: Optional[int] = Field(None, description="项目id")
    page_url: Optional[str] = Field(None, description="URL")
    token_id: Optional[int] = Field(None, description="tokenId")
    function: Optional[str] = Field(None, description="功能")
    remark: Optional[str] = Field(None, description="备注")


class PageInfoCreate(PageInfoBase):
    """页面信息创建Schema"""
    pass


class PageInfoUpdate(PageInfoBase):
    """页面信息更新Schema"""
    pass


class PageInfoInfo(PageInfoBase):
    """页面信息响应Schema"""
    page_id: Optional[int] = Field(None, description="主键")
    creator: Optional[str] = Field(None, description="创建人")
    create_time: Optional[datetime] = Field(None, description="创建时间")
    update_time: Optional[datetime] = Field(None, description="更新时间")

    @field_serializer('create_time', 'update_time')
    def serialize_datetime(self, dt: Optional[datetime], _info) -> Optional[str]:
        """时间字段自动转换为字符串格式"""
        if dt is None:
            return None
        return dt.strftime('%Y-%m-%d %H:%M:%S')
