"""
项目信息Schema
Generated by scaffold script
"""
from pydantic import BaseModel, ConfigDict, Field, field_serializer
from pydantic.alias_generators import to_camel
from typing import Optional
from datetime import datetime


class ProjectInfoBase(BaseModel):
    """项目信息基础Schema"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True
    )
    
    project_name: Optional[str] = Field(None, description="项目名称")
    project_address: Optional[str] = Field(None, description="项目地址")
    project_swagger: Optional[str] = Field(None, description="项目端口")
    project_env: Optional[str] = Field(None, description="项目环境")
    version: Optional[str] = Field(None, description="项目版本")
    remark: Optional[str] = Field(None, description="备注")
    status: Optional[int] = Field(None, description="状态")


class ProjectInfoCreate(ProjectInfoBase):
    """项目信息创建Schema"""
    pass


class ProjectInfoUpdate(ProjectInfoBase):
    """项目信息更新Schema"""
    project_id: int = Field(..., description="主键")


class ProjectInfoInfo(ProjectInfoBase):
    """项目信息响应Schema"""
    project_id: Optional[int] = Field(None, description="主键")
    creator: Optional[str] = Field(None, description="创建人")
    create_time: Optional[datetime] = Field(None, description="创建时间")
    update_time: Optional[datetime] = Field(None, description="更新时间")

    @field_serializer('create_time', 'update_time')
    def serialize_datetime(self, dt: Optional[datetime], _info) -> Optional[str]:
        """时间字段自动转换为字符串格式"""
        if dt is None:
            return None
        return dt.strftime('%Y-%m-%d %H:%M:%S')
