"""
系统用户Schema
Generated by scaffold script
"""
from pydantic import BaseModel, ConfigDict, Field, field_serializer
from pydantic.alias_generators import to_camel
from typing import Optional
from datetime import datetime


class SysUserBase(BaseModel):
    """系统用户基础Schema"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True
    )
    
    nickname: Optional[str] = Field(None, description="用户昵称")
    username: Optional[str] = Field(None, description="用户名")
    password: Optional[str] = Field(None, description="密码")
    dept_id: Optional[int] = Field(None, description="部门id")
    status: Optional[int] = Field(None, description="状态")
    remark: Optional[str] = Field(None, description="备注")


class SysUserCreate(SysUserBase):
    """系统用户创建Schema"""
    pass


class SysUserUpdate(SysUserBase):
    """系统用户更新Schema"""
    pass


class SysUserInfo(SysUserBase):
    """系统用户响应Schema"""
    user_id: Optional[int] = Field(None, description="用户id")
    creator: Optional[str] = Field(None, description="创建人")
    create_time: Optional[datetime] = Field(None, description="创建时间")
    update_time: Optional[datetime] = Field(None, description="更新时间")

    @field_serializer('create_time', 'update_time')
    def serialize_datetime(self, dt: Optional[datetime], _info) -> Optional[str]:
        """时间字段自动转换为字符串格式"""
        if dt is None:
            return None
        return dt.strftime('%Y-%m-%d %H:%M:%S')
