"""
Token信息Schema
Generated by scaffold script
"""
from pydantic import BaseModel, ConfigDict, Field, field_serializer
from pydantic.alias_generators import to_camel
from typing import Optional
from datetime import datetime

from models.project_info_model import ProjectInfo
from models.token_info_model import TokenInfo



class TokenInfoBase(BaseModel):
    """Token信息基础Schema"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True
    )
    name: Optional[str] = Field(None, description="名称")
    type: Optional[int] = Field(None, description="类型")
    token_type: Optional[int] = Field(1, description="token类型 1api 2web")

class TokenInfoCreate(TokenInfoBase):
    """Token信息创建Schema"""
    token: Optional[str] = Field(None, description="token") 
    project_id: Optional[int] = Field(None, description="项目id")
    instance_id: Optional[int] = Field(None, description="实例id")
    status: Optional[int] = Field(None, description="状态")
    remark: Optional[str] = Field(None, description="备注")


class TokenInfoUpdate(TokenInfoBase):
    """Token信息更新Schema"""
    token: Optional[str] = Field(None, description="token")
    token_id: int = Field(..., description="tokenId")
    project_id: Optional[int] = Field(None, description="项目id")
    instance_id: Optional[int] = Field(None, description="实例id")
    status: Optional[int] = Field(None, description="状态")
    remark: Optional[str] = Field(None, description="备注")

class TokenInfoList(TokenInfoBase):
    """Token信息列表Schema"""
    token_type: Optional[int] = Field(None, description="token类型 1api 2web")
    page_num: int = Field(default=1, description="页码")
    page_size: int = Field(default=10, description="页大小")
    project_address: Optional[str] = Field(None, description="项目地址")
    project_id: Optional[int] = Field(None, description="项目id")
    def filter_params(self):
        filter_params = []
        if self.project_id is not None:
            filter_params.append(TokenInfo.project_id == self.project_id)
        if self.type is not None:
            filter_params.append(TokenInfo.type == self.type)
        if self.token_type is not None:
            filter_params.append(TokenInfo.token_type == self.token_type)
        if self.project_address is not None:
            filter_params.append(ProjectInfo.project_address.contains(self.project_address))
        if self.name is not None:
            filter_params.append(TokenInfo.name.contains(self.name))
        return filter_params


class TokenInfoIds(BaseModel):
    ids: list[int] = Field(..., description="Token ID列表")

class TokenInfoInfo(TokenInfoBase):
    """Token信息响应Schema"""
    token_id: Optional[int] = Field(None, description="tokenId")
    project_name: Optional[str] = Field(None, description="项目名称")
    project_address: Optional[str] = Field(None, description="项目地址")
    creator: Optional[str] = Field(None, description="创建人")
    create_time: Optional[datetime] = Field(None, description="创建时间")
    update_time: Optional[datetime] = Field(None, description="更新时间")
    project_id: Optional[int] = Field(None, description="项目id")
    instance_id: Optional[int] = Field(None, description="实例id")
    api_id: Optional[int] = Field(None, description="API ID")
    api_name: Optional[str] = Field(None, description="API名称")
    api_instance_name: Optional[str] = Field(None, description="API实例名称")
    page_id: Optional[int] = Field(None, description="页面ID")
    page_name: Optional[str] = Field(None, description="页面名称")
    page_instance_name: Optional[str] = Field(None, description="页面实例名称")
    token: Optional[str] = Field(None, description="token")
    status: Optional[int] = Field(None, description="状态")
    remark: Optional[str] = Field(None, description="备注")

    @field_serializer('create_time', 'update_time')
    def serialize_datetime(self, dt: Optional[datetime], _info) -> Optional[str]:
        """时间字段自动转换为字符串格式"""
        if dt is None:
            return None
        return dt.strftime('%Y-%m-%d %H:%M:%S')
