"""
接口信息API路由
Generated by scaffold script
"""
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from typing import List
from core.db import get_db
from schemas.api_info_schemas import ApiInfoCreate, ApiInfoUpdate, ApiInfoList, ApiInfoInfo, BatchDeleteRequest
from service.api_info_service import (
    get_api_info_service,
    get_api_info_list_service,
    create_api_info_service,
    update_api_info_service,
    delete_api_info_service,
    delete_api_info_batch_service,
)

router = APIRouter()


@router.get("/apiInfo", response_model=dict)
async def list_api_info(
    data: ApiInfoList = Depends(),
    db: Session = Depends(get_db)
):
    """获取接口信息分页列表"""
    return await get_api_info_list_service(db, data=data)


@router.get("/apiInfo/{item_id}", response_model=dict)
async def get_api_info(
    item_id: int,
    db: Session = Depends(get_db)
):
    """获取接口信息详情"""
    return await get_api_info_service(db, item_id)


@router.post("/apiInfo", response_model=dict)
async def create_api_info(
    data: ApiInfoCreate,
    db: Session = Depends(get_db)
):
    """创建接口信息"""
    return await create_api_info_service(db, data)


@router.put("/apiInfo", response_model=dict)
async def update_api_info(
    data: ApiInfoUpdate,
    db: Session = Depends(get_db)
):
    """更新接口信息"""
    return await update_api_info_service(db, data)

@router.delete("/apiInfo/batch", response_model=dict)
async def delete_api_info_batch(
    request: BatchDeleteRequest, 
    db: Session = Depends(get_db)
):
    """删除接口信息"""
    return await delete_api_info_batch_service(db, request.ids)

@router.delete("/apiInfo/{item_id}", response_model=dict)
async def delete_api_info(
    item_id: int,
    db: Session = Depends(get_db)
):
    """删除接口信息"""
    return await delete_api_info_service(db, item_id)



