"""
接口模板API路由
Generated by scaffold script
"""
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from typing import List, Optional
from core.db import get_db
from schemas.api_template_schemas import ApiTemplateCreate, ApiTemplateUpdate, ApiTemplateInfo, ApiTemplateList
from service.api_template_service import (
    get_api_template_service,
    get_api_template_list_service,
    create_api_template_service,
    update_api_template_service,
    delete_api_template_service,
    export_api_templates_service
)

router = APIRouter()


@router.get("/apiTemplate", response_model=dict)
async def list_api_template(
    data: ApiTemplateList = Depends(),
    db: Session = Depends(get_db)
):
    """获取接口模板分页列表"""
    return await get_api_template_list_service(db, data)


@router.get("/apiTemplate/{item_id}", response_model=dict)
async def get_api_template(
    item_id: int,
    db: Session = Depends(get_db)
):
    """获取接口模板详情"""
    return await get_api_template_service(db, item_id)


@router.post("/apiTemplate", response_model=dict)
async def create_api_template(
    data: ApiTemplateCreate,
    db: Session = Depends(get_db)
):
    """创建接口模板"""
    return await create_api_template_service(db, data)


@router.put("/apiTemplate", response_model=dict)
async def update_api_template(
    data: ApiTemplateUpdate,
    db: Session = Depends(get_db)
):
    """更新接口模板"""
    return await update_api_template_service(db,  data)


@router.delete("/apiTemplate/{item_id}", response_model=dict)
async def delete_api_template(
    item_id: int,
    db: Session = Depends(get_db)
):
    """删除接口模板"""
    return await delete_api_template_service(db, item_id)


@router.get("/apiTemplate/export", response_model=dict)
async def export_api_templates(
    api_id: Optional[int] = Query(None, description="API ID，为空则导出全部"),
    format_type: str = Query("excel", description="导出格式: excel 或 csv"),
    db: Session = Depends(get_db)
):
    """导出API模板信息"""
    return await export_api_templates_service(db, api_id=api_id, format_type=format_type)
