"""
参数实例API路由
Generated by scaffold script
"""
from fastapi import APIRouter, Depends, HTTPException, Query, UploadFile, File
from sqlalchemy.orm import Session
from typing import List
from core.db import get_db
from schemas.api_instance_schemas import ApiInstanceCreate, ApiInstanceUpdate, ApiInstanceInfo, ApiInstanceList
from service.api_instance_service import (
    get_api_instance_service,
    get_api_instance_list_service,
    create_api_instance_service,
    update_api_instance_service,
    delete_api_instance_service,
    import_test_instances_service
)

router = APIRouter()


@router.get("/apiInstance", response_model=dict)
async def list_api_instance(
    data: ApiInstanceList = Depends(),
    db: Session = Depends(get_db)
):
    """获取参数实例分页列表"""
    return await get_api_instance_list_service(db, data)


@router.get("/apiInstance/{inatanceId}", response_model=dict)
async def get_api_instance(
    inatanceId: int,
    db: Session = Depends(get_db)
):
    """获取参数实例详情"""
    return await get_api_instance_service(db,item_id= inatanceId)


@router.post("/apiInstance", response_model=dict)
async def create_api_instance(
    data: ApiInstanceCreate,
    db: Session = Depends(get_db)
):
    """创建参数实例"""
    return await create_api_instance_service(db, data)


@router.put("/apiInstance", response_model=dict)
async def update_api_instance(
    data: ApiInstanceUpdate,
    db: Session = Depends(get_db)
):
    """更新参数实例"""
    return await update_api_instance_service(db, data)


@router.delete("/apiInstance/{inatanceId}", response_model=dict)
async def delete_api_instance(
    inatanceId: int,
    db: Session = Depends(get_db)
):
    """删除参数实例"""
    return await delete_api_instance_service(db,item_id= inatanceId)


@router.post("/apiInstance/import", response_model=dict)
async def import_api_instances(
    api_id: int,
    file: UploadFile = File(...),
    db: Session = Depends(get_db)
):
    """导入测试用例"""
    return await import_test_instances_service(db, api_id=api_id, file=file)
