"""
API执行路由
Generated by scaffold script
"""
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from core.db import get_db
from schemas.api_execute_schemas import ApiExecuteRequest
from service.api_execute_service import execute_api_service

router = APIRouter(prefix="/apiExecute", tags=["API执行"])


@router.post("/execute", summary="执行API测试用例")
async def execute_api(
    request: ApiExecuteRequest,
    db: Session = Depends(get_db)
):
    """
    统一执行入口
    
    - **execution_type**: 1-单实例, 2-批量实例, 3-API下所有实例, 4-项目下所有实例
    - **target_id**: 目标ID (根据类型传入 instance_id / api_id / project_id)
    - **target_ids**: 目标ID列表 (仅当 execution_type=2 时使用)
    """
    return await execute_api_service(db, request)
