"""
字典信息API路由
Generated by scaffold script
"""
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from typing import List
from core.db import get_db
from schemas.dict_info_schemas import DictInfoCreate, DictInfoUpdate, DictInfoInfo
from service.dict_info_service import (
    get_dict_info_service,
    get_dict_info_list_service,
    create_dict_info_service,
    update_dict_info_service,
    delete_dict_info_service
)

router = APIRouter(prefix="/dictInfo", tags=["字典信息"])


@router.get("/", response_model=dict)
async def list_dict_info(
    page_num: int = Query(default=1, ge=1, description="页码"),
    page_size: int = Query(default=10, ge=1, le=100, description="每页大小"),
    db: Session = Depends(get_db)
):
    """获取字典信息分页列表"""
    return await get_dict_info_list_service(db, page_num, page_size)


@router.get("/{item_id}", response_model=dict)
async def get_dict_info(
    item_id: int,
    db: Session = Depends(get_db)
):
    """获取字典信息详情"""
    return await get_dict_info_service(db, item_id)


@router.post("/", response_model=dict)
async def create_dict_info(
    data: DictInfoCreate,
    db: Session = Depends(get_db)
):
    """创建字典信息"""
    return await create_dict_info_service(db, data)


@router.put("/{item_id}", response_model=dict)
async def update_dict_info(
    item_id: int,
    data: DictInfoUpdate,
    db: Session = Depends(get_db)
):
    """更新字典信息"""
    return await update_dict_info_service(db, item_id, data)


@router.delete("/{item_id}", response_model=dict)
async def delete_dict_info(
    item_id: int,
    db: Session = Depends(get_db)
):
    """删除字典信息"""
    return await delete_dict_info_service(db, item_id)
