"""
元素模板API路由
Generated by scaffold script
"""
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from typing import List
from core.db import get_db
from schemas.element_template_schemas import ElementTemplateCreate, ElementTemplateUpdate, ElementTemplateInfo
from service.element_template_service import (
    get_element_template_service,
    get_element_template_list_service,
    create_element_template_service,
    update_element_template_service,
    delete_element_template_service
)

router = APIRouter(prefix="/elementTemplate", tags=["元素模板"])


@router.get("/", response_model=dict)
async def list_element_template(
    page_num: int = Query(default=1, ge=1, description="页码"),
    page_size: int = Query(default=10, ge=1, le=100, description="每页大小"),
    db: Session = Depends(get_db)
):
    """获取元素模板分页列表"""
    return await get_element_template_list_service(db, page_num, page_size)


@router.get("/{item_id}", response_model=dict)
async def get_element_template(
    item_id: int,
    db: Session = Depends(get_db)
):
    """获取元素模板详情"""
    return await get_element_template_service(db, item_id)


@router.post("/", response_model=dict)
async def create_element_template(
    data: ElementTemplateCreate,
    db: Session = Depends(get_db)
):
    """创建元素模板"""
    return await create_element_template_service(db, data)


@router.put("/{item_id}", response_model=dict)
async def update_element_template(
    item_id: int,
    data: ElementTemplateUpdate,
    db: Session = Depends(get_db)
):
    """更新元素模板"""
    return await update_element_template_service(db, item_id, data)


@router.delete("/{item_id}", response_model=dict)
async def delete_element_template(
    item_id: int,
    db: Session = Depends(get_db)
):
    """删除元素模板"""
    return await delete_element_template_service(db, item_id)
