"""
流程信息API路由
Generated by scaffold script
"""
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from typing import List
from core.db import get_db
from schemas.flow_info_schemas import FlowInfoCreate, FlowInfoUpdate, FlowInfoInfo
from service.flow_info_service import (
    get_flow_info_service,
    get_flow_info_list_service,
    create_flow_info_service,
    update_flow_info_service,
    delete_flow_info_service
)

router = APIRouter(prefix="/flowInfo", tags=["流程信息"])


@router.get("/", response_model=dict)
async def list_flow_info(
    page_num: int = Query(default=1, ge=1, description="页码"),
    page_size: int = Query(default=10, ge=1, le=100, description="每页大小"),
    db: Session = Depends(get_db)
):
    """获取流程信息分页列表"""
    return await get_flow_info_list_service(db, page_num, page_size)


@router.get("/{item_id}", response_model=dict)
async def get_flow_info(
    item_id: int,
    db: Session = Depends(get_db)
):
    """获取流程信息详情"""
    return await get_flow_info_service(db, item_id)


@router.post("/", response_model=dict)
async def create_flow_info(
    data: FlowInfoCreate,
    db: Session = Depends(get_db)
):
    """创建流程信息"""
    return await create_flow_info_service(db, data)


@router.put("/{item_id}", response_model=dict)
async def update_flow_info(
    item_id: int,
    data: FlowInfoUpdate,
    db: Session = Depends(get_db)
):
    """更新流程信息"""
    return await update_flow_info_service(db, item_id, data)


@router.delete("/{item_id}", response_model=dict)
async def delete_flow_info(
    item_id: int,
    db: Session = Depends(get_db)
):
    """删除流程信息"""
    return await delete_flow_info_service(db, item_id)
