"""
页面信息API路由
Generated by scaffold script
"""
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from typing import List
from core.db import get_db
from schemas.page_info_schemas import PageInfoCreate, PageInfoUpdate, PageInfoInfo
from service.page_info_service import (
    get_page_info_service,
    get_page_info_list_service,
    create_page_info_service,
    update_page_info_service,
    delete_page_info_service
)

router = APIRouter(prefix="/ pageInfo", tags=["页面信息"])


@router.get("/", response_model=dict)
async def list_page_info(
    page_num: int = Query(default=1, ge=1, description="页码"),
    page_size: int = Query(default=10, ge=1, le=100, description="每页大小"),
    db: Session = Depends(get_db)
):
    """获取页面信息分页列表"""
    return await get_page_info_list_service(db, page_num, page_size)


@router.get("/{item_id}", response_model=dict)
async def get_page_info(
    item_id: int,
    db: Session = Depends(get_db)
):
    """获取页面信息详情"""
    return await get_page_info_service(db, item_id)


@router.post("/", response_model=dict)
async def create_page_info(
    data: PageInfoCreate,
    db: Session = Depends(get_db)
):
    """创建页面信息"""
    return await create_page_info_service(db, data)


@router.put("/{item_id}", response_model=dict)
async def update_page_info(
    item_id: int,
    data: PageInfoUpdate,
    db: Session = Depends(get_db)
):
    """更新页面信息"""
    return await update_page_info_service(db, item_id, data)


@router.delete("/{item_id}", response_model=dict)
async def delete_page_info(
    item_id: int,
    db: Session = Depends(get_db)
):
    """删除页面信息"""
    return await delete_page_info_service(db, item_id)
