"""
项目信息API路由
Generated by scaffold script
"""
from fastapi import APIRouter, Depends, HTTPException, Query, Query
from sqlalchemy.orm import Session
from typing import List
from core.db import get_db
from schemas.project_info_schemas import ProjectInfoCreate, ProjectInfoUpdate, ProjectInfoInfo
from service.project_info_service import (
    get_project_info_service,
    get_project_info_list_service,
    create_project_info_service,
    update_project_info_service,
    delete_project_info_service
)

router = APIRouter()


@router.get("/projectInfo", response_model=dict)
async def list_project_info(
    pageNum: int = Query(default=1, ge=1, description="页码"),
    pageSize: int = Query(default=10, ge=1, le=1000, description="每页大小"),
    db: Session = Depends(get_db)
):
    """获取项目信息分页分页列表"""
    return await get_project_info_list_service(db, page_num = pageNum, page_size = pageSize)


@router.get("/projectInfo/{item_id}", response_model=dict)
async def get_project_info(
    item_id: int,
    db: Session = Depends(get_db)
):
    """获取项目信息详情"""
    return await get_project_info_service(db, item_id)


@router.post("/projectInfo", response_model=dict)
async def create_project_info(
    data: ProjectInfoCreate,
    db: Session = Depends(get_db)
):
    """创建项目信息"""
    return await create_project_info_service(db, data)


@router.put("/projectInfo", response_model=dict)
async def update_project_info(
    data: ProjectInfoUpdate,
    db: Session = Depends(get_db)
):
    print("更新项目信息接口被调用，接收到的数据：", data)
    """更新项目信息"""
    return await update_project_info_service(db, data)


@router.delete("/projectInfo/{item_id}", response_model=dict)
async def delete_project_info(
    item_id: int,
    db: Session = Depends(get_db)
):
    """删除项目信息"""
    return await delete_project_info_service(db, item_id)
