"""
Token信息API路由
Generated by scaffold script
"""
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from typing import List
from core.db import get_db
from schemas.token_info_schemas import TokenInfoCreate,TokenInfoList, TokenInfoUpdate, TokenInfoInfo
from service.token_info_service import (
    get_token_info_service,
    get_token_info_list_service,
    create_token_info_service,
    update_token_info_service,
    delete_token_info_service
)

router = APIRouter()


@router.get("/tokenInfo", response_model=dict)
async def list_token_info(
    search_params: TokenInfoList = Depends(),
    db: Session = Depends(get_db)
):
    """获取Token信息分页列表"""
    return await get_token_info_list_service(db, filter = search_params)


@router.get("/tokenInfo/{item_id}", response_model=dict)
async def get_token_info(
    item_id: int,
    db: Session = Depends(get_db)
):
    """获取Token信息详情"""
    return await get_token_info_service(db, item_id)


@router.post("/tokenInfo", response_model=dict)
async def create_token_info(
    data: TokenInfoCreate,
    db: Session = Depends(get_db)
):
    """创建Token信息"""
    return await create_token_info_service(db, data)


@router.put("/tokenInfo", response_model=dict)
async def update_token_info(
    data: TokenInfoUpdate,
    db: Session = Depends(get_db)
):
    """更新Token信息"""
    return await update_token_info_service(db,  data)


@router.delete("/tokenInfo/{item_id}", response_model=dict)
async def delete_token_info(
    item_id: int,
    db: Session = Depends(get_db)
):
    """删除Token信息"""
    return await delete_token_info_service(db, item_id)
