"""
Token信息API路由
Generated by scaffold script
"""
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from typing import List
from core.db import get_db
from schemas.token_info_schemas import TokenInfoCreate, TokenInfoIds, TokenInfoList, TokenInfoUpdate, TokenInfoInfo
from service.token_info_service import (
    get_token_info_service,
    get_token_info_list_service,
    get_token_info_options_service,
    get_token_info_select_options_service,
    create_token_info_service,
    update_token_info_service,
    delete_token_info_service,
    delete_token_info_batch_service,
    refresh_token_service
)

router = APIRouter()


@router.get("/tokenInfo", response_model=dict)
async def list_token_info(
    search_params: TokenInfoList = Depends(),
    db: Session = Depends(get_db)
):
    """获取Token信息分页列表"""
    return await get_token_info_list_service(db, filter = search_params)


@router.get("/tokenInfo/options", response_model=dict)
async def list_token_info_options(
    token_type: int = Query(..., alias="tokenType", description="来源 1 api 2 web"),
    project_id: int | None = Query(None, alias="projectId", description="项目ID"),
    name: str | None = Query(None, description="Token名称"),
    db: Session = Depends(get_db)
):
    """获取Token下拉框列表，来源必填"""
    return await get_token_info_options_service(
        db=db,
        token_type=token_type,
        project_id=project_id,
        name=name
    )


@router.get("/tokenInfo/selectOptions", response_model=dict)
async def list_token_info_select_options(
    project_id: int | None = Query(None, alias="projectId", description="项目ID"),
    token_type: int | None = Query(None, alias="tokenType", description="来源 1 api 2 web"),
    name: str | None = Query(None, description="Token名称"),
    db: Session = Depends(get_db)
):
    """获取轻量Token下拉框列表，不需要分页参数。"""
    return await get_token_info_select_options_service(
        db=db,
        project_id=project_id,
        token_type=token_type,
        name=name
    )


@router.post("/tokenInfo", response_model=dict)
async def create_token_info(
    data: TokenInfoCreate,
    db: Session = Depends(get_db)
):
    """创建Token信息"""
    return await create_token_info_service(db, data)


@router.put("/tokenInfo", response_model=dict)
async def update_token_info(
    data: TokenInfoUpdate,
    db: Session = Depends(get_db)
):
    """更新Token信息"""
    return await update_token_info_service(db,  data)


@router.delete("/tokenInfo/batch", response_model=dict)
async def delete_token_info_batch(
    data: TokenInfoIds,
    db: Session = Depends(get_db)
):
    """批量删除Token信息"""
    return await delete_token_info_batch_service(db, data.ids)


@router.post("/tokenInfo/refresh/batch", response_model=dict)
async def refresh_token_batch(
    data: TokenInfoIds,
    db: Session = Depends(get_db)
):
    """批量刷新Token"""
    results = []
    for token_id in data.ids:
        results.append(await refresh_token_service(db, token_id))
    failed = [item for item in results if not item.get("success")]
    return {
        "success": len(failed) == 0,
        "msg": "批量刷新成功" if not failed else "批量刷新部分失败",
        "data": {"results": results, "failed": failed}
    }


@router.get("/tokenInfo/{item_id}", response_model=dict)
async def get_token_info(
    item_id: int,
    db: Session = Depends(get_db)
):
    """获取Token信息详情"""
    return await get_token_info_service(db, item_id)


@router.delete("/tokenInfo/{item_id}", response_model=dict)
async def delete_token_info(
    item_id: int,
    db: Session = Depends(get_db)
):
    """删除Token信息"""
    return await delete_token_info_service(db, item_id)


@router.post("/tokenInfo/refresh/{token_id}", response_model=dict)
async def refresh_token(
    token_id: int,
    db: Session = Depends(get_db)
):
    """刷新Token
    
    根据Token关联的instance_id重新执行API，解析响应中的token并更新到Token表
    """
    return await refresh_token_service(db, token_id)
