"""
参数实例Service层
Generated by scaffold script
"""
import json
import time
import pandas as pd
from sqlalchemy.orm import Session
from schemas.api_instance_schemas import ApiInstanceCreate, ApiInstanceUpdate, ApiInstanceInfo, ApiInstanceList
from mysql.api_instance_sql import (
    get_api_instance_by_id,
    get_api_instance_by_unique_fields,
    get_api_instance_list,
    create_api_instance,
    update_api_instance,
    delete_api_instance
)
from mysql.api_result_sql import delete_api_result_by_instance_id
from utils.pagination import create_page_response
from core.responsemsg import success_response, error_response


async def get_api_instance_service(db: Session, item_id: int):
    """获取参数实例详情"""
    obj = await get_api_instance_by_id(db, item_id)
    if not obj:
        return error_response(
            msg="查询失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "参数实例不存在"}'
        )
    
    # 将ORM对象转换为Schema对象
    schema_obj = ApiInstanceInfo.model_validate(obj)
    return success_response(msg="查询成功", data=schema_obj)


async def get_api_instance_list_service(db: Session, data: ApiInstanceList):
    """获取参数实例分页列表"""
    items, total = await get_api_instance_list(db, data)
    
    # 将ORM对象转换为Schema对象
    schema_items = [ApiInstanceInfo.model_validate(item) for item in items]
    
    # 构建分页响应
    page_data = create_page_response(
        items=schema_items,
        total=total,
        page_num=data.page_num,
        page_size=data.page_size
    )
    
    return success_response(msg="查询成功", data=page_data)


async def create_api_instance_service(db: Session, data: ApiInstanceCreate):
    """创建参数实例"""
    # 业务逻辑校验：检查是否存在相同的api_id和instance_name组合
    existing = await get_api_instance_by_unique_fields(
        db, 
        api_id=data.api_id,
        instance_name=data.instance_name
    )
    
    if existing:
        return error_response(
            msg="添加失败，该实例已存在",
            data=existing,
            error=f'{{"errorCode": "DUPLICATE_INSTANCE", "message": "API ID为{data.api_id}的实例中，已存在名称为\'{data.instance_name}\'的参数实例"}}'
        )
    
    obj = await create_api_instance(db, data.model_dump(by_alias=False))
    
    # 将ORM对象转换为Schema对象
    schema_obj = ApiInstanceInfo.model_validate(obj)
    return success_response(msg="添加成功", data=schema_obj)


async def update_api_instance_service(db: Session,  data: ApiInstanceUpdate):
    """更新参数实例"""
    # 校验是否存在
    existing = await get_api_instance_by_id(db, data.instance_id)
    if not existing:
        return error_response(
            msg="更新失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "参数实例不存在"}'
        )
    
    obj = await update_api_instance(db, data.instance_id, data.model_dump(by_alias=False, exclude_unset=True))
    
    # 将ORM对象转换为Schema对象
    schema_obj = ApiInstanceInfo.model_validate(obj)
    return success_response(msg="更新成功", data=schema_obj)


async def delete_api_instance_service(db: Session, item_id: int):
    """删除参数实例"""
    # 校验是否存在
    existing = await get_api_instance_by_id(db, item_id)
    if not existing:
        return error_response(
            msg="删除失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "参数实例不存在"}'
        )
    # 删除关联的测试用例
    await delete_api_result_by_instance_id(db, item_id)
    # 删除参数实例本身
    obj = await delete_api_instance(db, item_id)
    
    return success_response(
        msg="删除成功",
        data={"id": item_id, "message": "参数实例已删除"}
    )


async def import_test_instances_service(db: Session, api_id: int, file):
    """导入测试用例"""
    try:
        # 1. 读取文件
        if file.filename.endswith('.csv'):
            df = pd.read_csv(file.file)
        elif file.filename.endswith('.xlsx'):
            df = pd.read_excel(file.file)
        else:
            return error_response(msg="不支持的文件格式，请上传 CSV 或 XLSX 文件")
            
        # 2. 获取该 API 的模板信息，用于确定唯一字段
        from mysql.api_template_sql import get_api_template_list_by_api_id
        templates = await get_api_template_list_by_api_id(db, api_id)
        if not templates:
            return error_response(msg="该接口暂无模板定义，无法导入用例")
        
        # 假设第一个字段为唯一标识字段（或者根据业务逻辑指定）
        unique_field = templates[0].field_name
        
        saved_count = 0
        timestamp = str(int(time.time()))
        
        for _, row in df.iterrows():
            instance_name = str(row.iloc[0])
            instance_json_str = str(row.iloc[1])
            expect_result = str(row.iloc[2]) if len(row) > 2 else ""
            
            # 更新用例 JSON 中对应唯一字段的值
            try:
                instance_data = json.loads(instance_json_str)
                if unique_field in instance_data:
                    instance_data[unique_field] = f"{instance_data[unique_field]}_{timestamp}"
                instance_json_updated = json.dumps(instance_data)
            except:
                instance_json_updated = instance_json_str
                
            # 唯一性校验：用例名称 + api_id
            existing = await get_api_instance_by_unique_fields(db, api_id, instance_name)
            if not existing:
                data = {
                    "instance_name": instance_name,
                    "api_id": api_id,
                    "instance_json": instance_json_updated,
                    "expect_result": expect_result,
                    "status": 1
                }
                data = set_audit_fields_for_create(data)
                data['creator'] = 'Import'
                await create_api_instance(db, data)
                saved_count += 1
                
        return success_response(msg=f"成功导入 {saved_count} 条用例", data={"count": saved_count})
    except Exception as e:
        return error_response(msg=f"导入失败: {str(e)}")
