"""
接口模板Service层
Generated by scaffold script
"""
from fastapi.responses import StreamingResponse
import pandas as pd
import io
from sqlalchemy.orm import Session
from schemas.api_template_schemas import ApiTemplateCreate, ApiTemplateUpdate, ApiTemplateInfo, ApiTemplateList
from mysql.api_template_sql import (
    get_api_template_by_id,
    get_api_template_by_unique_fields,
    get_api_template_list,
    create_api_template,
    update_api_template,
    delete_api_template
)
from models.api_template_model import ApiTemplate
from utils.pagination import create_page_response
from core.responsemsg import success_response, error_response


async def get_api_template_service(db: Session, item_id: int):
    """获取接口模板详情"""
    obj = await get_api_template_by_id(db, item_id)
    if not obj:
        return error_response(
            msg="查询失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "接口模板不存在"}'
        )

    """将ORM对象转换为Schema对象"""
    schema_obj = ApiTemplateInfo.model_validate(obj)
    return success_response(msg="查询成功", data=schema_obj)


async def get_api_template_list_service(db: Session, data: ApiTemplateList):
    """获取接口模板分页列表（含关联信息）"""
    items, total = await get_api_template_list(db, data)

    """将字典转换为Schema对象"""
    schema_items = [ApiTemplateInfo.model_validate(item) for item in items]

    """构建分页响应"""
    page_data = create_page_response(
        items=schema_items,
        total=total,
        page_num=data.page_num,
        page_size=data.page_size
    )

    return success_response(msg="查询成功", data=page_data)


async def create_api_template_service(db: Session, data: ApiTemplateCreate):
    """创建接口模板"""
    """业务逻辑校验：检查是否存在相同的api_id和field_name组合"""
    existing = await get_api_template_by_unique_fields(
        db,
        api_id=data.api_id,
        field_name=data.field_name
    )

    if existing:
        return error_response(
            msg="添加失败，该字段已存在",
            data=existing,
            error=f'{"errorCode": "DUPLICATE_TEMPLATE", "message": "API ID为{data.api_id}的模板中，已存在名称为\'{data.field_name}\'的字段"}'
        )

    obj = await create_api_template(db, data.model_dump(by_alias=False))

    """将ORM对象转换为Schema对象"""
    schema_obj = ApiTemplateInfo.model_validate(obj)
    return success_response(msg="添加成功", data=schema_obj)


async def update_api_template_service(db: Session,  data: ApiTemplateUpdate):
    """更新接口模板"""
    """校验是否存在"""
    existing = await get_api_template_by_id(db, data.template_id)
    if not existing:
        return error_response(
            msg="更新失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "接口模板不存在"}'
        )

    obj = await update_api_template(db, data.template_id, data.model_dump(by_alias=False, exclude_unset=True))

    """将ORM对象转换为Schema对象"""
    schema_obj = ApiTemplateInfo.model_validate(obj)
    return success_response(msg="更新成功", data=schema_obj)


async def delete_api_template_service(db: Session, item_id: int):
    """删除接口模板"""
    """校验是否存在"""
    existing = await get_api_template_by_id(db, item_id)
    if not existing:
        return error_response(
            msg="删除失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "接口模板不存在"}'
        )

    obj = await delete_api_template(db, item_id)

    return success_response(
        msg="删除成功",
        data={"id": item_id, "message": "接口模板已删除"}
    )


async def export_api_templates_service(db: Session, api_id: int = None, format_type: str = "excel"):
    """导出API模板信息"""
    query = db.query(ApiTemplate)
    if api_id:
        query = query.filter(ApiTemplate.api_id == api_id)
    
    templates = query.all()
    
    """转换为 DataFrame"""
    data = []
    for t in templates:
        data.append({
            "template_id": t.template_id,
            "field_name": t.field_name,
            "field_type": t.field_type,
            "field_size": t.field_size,
            "is_required": t.is_required,
            "api_id": t.api_id,
            "remark": t.remark
        })
    
    df = pd.DataFrame(data)
    
    if format_type == "csv":
        output = io.StringIO()
        df.to_csv(output, index=False, encoding='utf-8-sig')
        media_type = "text/csv"
        filename = "api_templates.csv"
        content = output.getvalue().encode('utf-8-sig')
    else:
        output = io.BytesIO()
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            df.to_excel(writer, index=False, sheet_name='Templates')
        media_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        filename = "api_templates.xlsx"
        content = output.getvalue()
        
    return StreamingResponse(
        iter([content]),
        media_type=media_type,
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
