"""
API执行Service层
Generated by scaffold script
"""
import time
import json
import requests
from concurrent.futures import ThreadPoolExecutor, as_completed
from sqlalchemy.orm import Session
from models.api_result_model import ApiResult
from schemas.api_execute_schemas import ApiExecuteRequest, ApiExecuteResult, BatchApiExecuteResult
from mysql.api_execute_sql import get_api_execution_context, get_instances_by_api_id, get_instances_by_project_id, update_api_instance_execute_state, get_existing_instance_ids
from mysql.api_result_sql import batch_create_api_results
from core.responsemsg import success_response, error_response
from core.logger import logger


"""HTTP方法映射"""
METHOD_MAP = {1: 'GET', 2: 'POST', 3: 'PUT', 4: 'DELETE', 5: 'PATCH'}


def _parse_json_object(raw) -> dict:
    if not raw:
        return {}
    if isinstance(raw, dict):
        return dict(raw)
    try:
        parsed = json.loads(raw)
        return parsed if isinstance(parsed, dict) else {}
    except json.JSONDecodeError:
        try:
            parsed = json.loads(raw, strict=False)
            return parsed if isinstance(parsed, dict) else {}
        except json.JSONDecodeError:
            return {}


def _get_batch_count(instance_json: dict) -> int:
    value = instance_json.get("batchCount", 1)
    try:
        count = int(value)
    except (TypeError, ValueError):
        count = 1
    return max(count, 1)


def _apply_value_marks(instance_json: dict, exec_count: int | None = 0) -> dict:
    result = dict(instance_json or {})
    value_marks = result.pop("valueMarks", None)
    result.pop("batchCount", None)
    if not isinstance(value_marks, dict):
        return result

    offset = (exec_count or 0) + 1
    for key, mark in value_marks.items():
        if mark != "execCountSuffix" or key not in result:
            continue
        value = result.get(key)
        if isinstance(value, (dict, list)) or value is None:
            continue
        if isinstance(value, str) and value.isdigit():
            result[key] = str(int(value) + offset)
        elif isinstance(value, (int, float)) and not isinstance(value, bool):
            result[key] = value + offset
        else:
            result[key] = f"{value}{offset}"
    return result


def _build_result_db_data(exec_result: dict) -> dict:
    status_code = exec_result.get('status_code') or 0
    is_normal = int(status_code) == 200
    return {
        "instance_id": exec_result['instance_id'],
        "result_status": 1 if is_normal else 2,
        "code": str(status_code) if status_code else "000",
        "response_info": exec_result['response_info'] if exec_result['response_info'] else exec_result.get('error_message', ''),
        "remark": f"耗时: {exec_result['execution_time']}s"
    }


def _build_and_send_request(context: dict, request_params: dict | None = None) -> dict:
    """核心逻辑：构建请求并发送"""
    instance = context['instance']
    api_info = context['api_info']
    project_info = context['project_info']
    token_info = context['token_info']
    
    start_time = time.time()
    result_data = {
        "instance_id": instance.instance_id,
        "success": False,
        "status_code": 0,
        "response_info": "",
        "execution_time": 0,
        "error_message": ""
    }
    
    try:
        if not project_info:
            raise Exception(f"项目ID {api_info.project_id} 不存在")
            
        """1. 拼接 URL"""
        base_url = project_info.project_address.rstrip('/')
        method_url = api_info.method_url.lstrip('/')
        url = f"{base_url}/{method_url}"
        
        """2. 准备 Headers"""
        headers = {}
        if api_info.request_header:
            try:
                headers.update(json.loads(api_info.request_header))
            except: pass
            
        if token_info and token_info.token:
            headers['Authorization'] = token_info.token
            
        """3. 准备参数 (根据 params_path 判断)"""
        params = None
        data = None
        json_data = None
        
        inst_json = request_params if request_params is not None else _parse_json_object(instance.instance_json)
        if inst_json:
            path_type = api_info.params_path.lower() if api_info.params_path else 'in'
            
            if path_type == 'data':
                data = inst_json
            elif path_type == 'body':
                json_data = inst_json
                headers['Content-Type'] = 'application/json'
            else:
                """'in' or others treated as query params"""
                params = inst_json
            
        """4. 发送请求"""
        method = METHOD_MAP.get(api_info.method_type, 'GET')
        response = requests.request(
            method=method,
            url=url,
            headers=headers,
            params=params,
            data=data,
            json=json_data,
            timeout=30
        )
        response.encoding = 'utf-8'
        logger.info(f"{instance.instance_name} - {api_info.api_name} - {method} - {url} - {response.status_code} - {response.text[:1000]}")
        result_data.update({
            "success": response.status_code == 200,
            "status_code": response.status_code,
            "code": str(response.status_code),
            "response_info": response.text[:10000],
            "execution_time": round(time.time() - start_time, 3)
        })
        
    except Exception as e:
        logger.exception(
            "API 执行异常: instance_id=%s, api_name=%s, method_url=%s",
            getattr(instance, "instance_id", None),
            getattr(api_info, "api_name", None),
            getattr(api_info, "method_url", None),
        )
        result_data.update({
            "success": False,
            "error_message": str(e),
            "execution_time": round(time.time() - start_time, 3)
        })
        
    return result_data


def _execute_context_task(context: dict) -> tuple[dict, int, bool]:
    instance = context["instance"]
    raw_instance_json = _parse_json_object(instance.instance_json)
    batch_count = _get_batch_count(raw_instance_json)
    base_exec_count = instance.exec_count or 0
    exec_result = None
    for index in range(batch_count):
        request_params = _apply_value_marks(raw_instance_json, base_exec_count + index)
        exec_result = _build_and_send_request(context, request_params)
    return _build_result_db_data(exec_result), batch_count, exec_result["success"]


def _execute_single_task(db: Session, instance_id: int, token_id: int | None = None) -> dict:
    """执行单个任务并返回结果字典（用于存入数据库）"""
    context = get_api_execution_context(db, instance_id, token_id=token_id)
    if not context:
        update_api_instance_execute_state(db, instance_id, False)
        return {
            "instance_id": instance_id,
            "result_status": 2,
            "code": "404",
            "response_info": json.dumps({"error": "Instance or related info not found"}),
            "remark": "执行失败：未找到相关配置"
        }
        
    result_db_data, batch_count, success = _execute_context_task(context)
    
    """更新执行次数"""
    update_api_instance_execute_state(db, instance_id, success, batch_count)
    
    return result_db_data

async def execute_api_service(db: Session, request: ApiExecuteRequest):
    """统一执行入口"""
    etype = request.execution_type
    tid = request.target_id
    tids = request.target_ids
    token_id = request.token_id
    
    instance_ids = []
    
    try:
        if etype == 1:
            """单实例"""
            if not tid: return error_response(msg="缺少 target_id")
            instance_ids = [tid]
        elif etype == 2:
            """批量实例"""
            if not tids: return error_response(msg="缺少 target_ids")
            instance_ids = tids
        elif etype == 3:
            """API下所有实例"""
            if not tid: return error_response(msg="缺少 target_id (api_id)")
            instances = await get_instances_by_api_id(db, tid)
            instance_ids = [i.instance_id for i in instances]
        elif etype == 4:
            """项目下所有实例"""
            if not tid: return error_response(msg="缺少 target_id (project_id)")
            instances = await get_instances_by_project_id(db, tid)
            instance_ids = [i.instance_id for i in instances]
        else:
            return error_response(msg=f"不支持的执行类型: {etype}")
            
        if not instance_ids:
            return success_response(msg="未找到可执行的测试用例", data=[])
            
        results = []
        """超过50条启用多线程执行 HTTP 请求"""
        if len(instance_ids) > 50:
            with ThreadPoolExecutor(max_workers=10) as executor:
                """注意：这里我们传递 db 是为了在线程中获取上下文，但为了线程安全，"""
                """更好的做法是主线程先查好所有上下文，或者在线程内创建新 session。"""
                """鉴于当前架构，我们暂时保持传递 db，但需注意 SQLAlchemy 配置。"""
                """优化：主线程先获取所有 context"""
                contexts = []
                for iid in instance_ids:
                    ctx = get_api_execution_context(db, iid, token_id=token_id)
                    if ctx:
                        contexts.append((iid, ctx))
                    else:
                        results.append({
                            "instance_id": iid,
                            "result_status": 2,
                            "code": "404",
                            "response_info": "Not Found",
                            "remark": "配置缺失"
                        })
                        update_api_instance_execute_state(db, iid, False)
                
                future_to_id = {executor.submit(_execute_context_task, ctx): iid for iid, ctx in contexts}
                for future in as_completed(future_to_id):
                    iid = future_to_id[future]
                    try:
                        result_db_data, batch_count, success = future.result()
                        results.append(result_db_data)
                        """更新执行次数（在主线程或单独处理，避免线程竞争）"""
                        update_api_instance_execute_state(db, iid, success, batch_count)
                    except Exception as e:
                        logger.exception("API 批量执行线程异常: instance_id=%s", iid)
                        results.append({"instance_id": iid, "response_info": str(e), "result_status": 2, "code": "500", "remark": "执行异常"})
                        update_api_instance_execute_state(db, iid, False)
        else:
            for iid in instance_ids:
                res = _execute_single_task(db, iid, token_id=token_id)
                results.append(res)
                
        """批量保存结果到 api_result"""
        """仅保存 instance_id 在 api_instance 中真实存在的结果，"""
        """否则会触发外键约束 fk_result_instance 失败（如执行了已删除/不存在的实例）。"""
        """未找到的实例仍保留在返回结果中用于前端展示，但不写库。"""
        if results:
            valid_instance_ids = get_existing_instance_ids(
                db, [r["instance_id"] for r in results]
            )
            persistable = [r for r in results if r["instance_id"] in valid_instance_ids]
            skipped = len(results) - len(persistable)
            if skipped:
                logger.warning(
                    f"跳过 {skipped} 条结果入库：对应 instance_id 在 api_instance 中不存在"
                )
            if persistable:
                await batch_create_api_results(db, persistable)

        return success_response(msg=f"执行完成，共 {len(results)} 条结果", data=results)
        
    except Exception as e:
        return error_response(msg=f"执行过程中发生错误: {str(e)}")
