"""
接口信息Service层
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from schemas.api_info_schemas import ApiInfoCreate, ApiInfoUpdate, ApiInfoInfo, ApiInfoList
from mysql.api_info_sql import (
    get_api_info_by_id,
    get_api_info_by_unique_fields,
    get_api_info_list,
    create_api_info,
    update_api_info,
    delete_api_info
)
from mysql.api_instance_sql import delete_api_instance_by_api_id
from mysql.api_template_sql import delete_api_template_by_api_id
from mysql.api_result_sql import delete_api_result_by_api_id
from utils.pagination import create_page_response
from core.responsemsg import success_response, error_response
from core.logger import logger


async def get_api_info_service(db: Session, item_id: int):
    """获取接口信息详情"""
    obj = await get_api_info_by_id(db, item_id)
    if not obj:
        return error_response(
            msg="查询失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "接口信息不存在"}'
        )

    return success_response(msg="查询成功", data=obj)


async def get_api_info_list_service(db: Session, data: ApiInfoList):
    """获取接口信息分页列表"""
    items, total = await get_api_info_list(db, data)
    
    # 将字典转换为Schema对象
    # schema_items = [ApiInfoInfo.model_validate(item) for item in items]
    
    # 构建分页响应
    page_data = create_page_response(
        items=items,
        total=total,
        page_num=data.page_num,
        page_size=data.page_size,
    )
    
    return success_response(msg="查询成功", data=page_data)


async def create_api_info_service(db: Session, data: ApiInfoCreate):
    """创建接口信息"""
    # 业务逻辑校验：检查是否存在相同的method_url、method_type和project_id组合
    existing = await get_api_info_by_unique_fields(
        db, 
        api_name=data.api_name,
        method_url=data.method_url,
        method_type=data.method_type,
        project_id=data.project_id
    )
    
    if existing:
        # 将ORM对象转换为Schema对象
        schema_existing = ApiInfoInfo.model_validate(existing)
        return error_response(
            msg="添加失败，该接口已存在",
            data=schema_existing,
            error=f'{{"errorCode": "DUPLICATE_API", "message": "项目ID为{data.project_id}的API中，已存在URL为\'{data.method_url}\'且方法类型为{data.method_type}的接口"}}'
        )
    
    obj = await create_api_info(db, data.model_dump(by_alias=False))
    
    # 将ORM对象转换为Schema对象
    schema_obj = ApiInfoInfo.model_validate(obj)
    return success_response(msg="添加成功", data=schema_obj)


async def update_api_info_service(db: Session,  data: ApiInfoUpdate):
    """更新接口信息"""
    # 校验是否存在
    obj = await update_api_info(db, data.api_id, data.model_dump(by_alias=False, exclude_unset=True))
    if not obj:
        return error_response(
            msg="更新失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "接口信息不存在"}'
        )
    existing = await get_api_info_by_unique_fields(
        db, 
        api_name=data.api_name,
        method_url=data.method_url,
        method_type=data.method_type,
        project_id=data.project_id
    )
    
    if existing and existing.api_id != obj.api_id:
        # 将ORM对象转换为Schema对象
        schema_existing = ApiInfoInfo.model_validate(existing)
        return error_response(
            msg="更新失败，该接口已存在",
            data=schema_existing,
            error=f'{{"errorCode": "DUPLICATE_API", "message": "项目ID为{data.project_id}的API中，已存在URL为\'{data.method_url}\'且方法类型为{data.method_type}的接口"}}'
        )
       
    # 将ORM对象转换为Schema对象
    schema_obj = ApiInfoInfo.model_validate(obj)
    return success_response(msg="更新成功", data=schema_obj)


async def delete_api_info_service(db: Session, item_id: int):
    """删除接口信息（级联删除关联数据）"""
    # 1. 校验是否存在
    obj = await get_api_info_by_id(db, item_id)
    if not obj:
        return error_response(
            msg="删除失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "接口信息不存在"}'
        )
    
    # 2. 级联删除关联的实例、模板和结果
    await delete_api_result_by_api_id(db, item_id)
    await delete_api_instance_by_api_id(db, item_id)
    await delete_api_template_by_api_id(db, item_id)
    
    # 3. 删除 API 本身
    result = await delete_api_info(db, item_id)
    
    if not result:
        return error_response(msg="删除失败", error="数据库删除操作未返回结果")
    
    return success_response(
        msg="删除成功",
        data={"id": item_id, "message": "接口信息及关联数据已删除"}
    )

async def delete_api_info_batch_service(db: Session, item_ids: list):
    """批量删除接口信息"""
    for item_id in item_ids:
        await delete_api_info_service(db, item_id)
    return success_response(msg="删除成功", data={"ids": item_ids, "message": "接口信息及关联数据已删除"})
