"""
接口模板Service层
Generated by scaffold script
"""
from fastapi.responses import StreamingResponse
import pandas as pd
import io
import json
from typing import Any, List, Tuple
from sqlalchemy.orm import Session
from schemas.api_template_schemas import ApiTemplateCreate, ApiTemplateUpdate, ApiTemplateInfo, ApiTemplateList, ApiTemplateJsonParse, ApiTemplateBatchDelete
from mysql.api_template_sql import (
    get_api_template_by_id,
    get_api_template_by_unique_fields,
    get_api_template_list,
    create_api_template,
    update_api_template,
    delete_api_template,
    delete_api_template_batch
)
from models.api_template_model import ApiTemplate
from models.api_info_model import ApiInfo
from utils.pagination import create_page_response
from core.responsemsg import success_response, error_response
from utils.data_paser import set_audit_fields_for_create


FIELD_TYPE_STRING = 1
FIELD_TYPE_NUMBER = 2
FIELD_TYPE_BOOLEAN = 3
FIELD_TYPE_ARRAY = 4
FIELD_TYPE_OBJECT = 5
MAX_FIELD_NAME_LENGTH = 50


def _json_value_type(value: Any) -> int:
    if isinstance(value, bool):
        return FIELD_TYPE_BOOLEAN
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return FIELD_TYPE_NUMBER
    if isinstance(value, list):
        return FIELD_TYPE_ARRAY
    if isinstance(value, dict):
        return FIELD_TYPE_OBJECT
    return FIELD_TYPE_STRING


def _json_value_size(value: Any) -> int:
    if value is None:
        return 0
    if isinstance(value, str):
        return len(value)
    if isinstance(value, (int, float, bool)):
        return len(str(value))
    if isinstance(value, (list, dict)):
        return len(value)
    return len(str(value))


def _json_sample(value: Any) -> str:
    try:
        sample = json.dumps(value, ensure_ascii=False)
    except TypeError:
        sample = str(value)
    return sample[:500]


def _json_default_value(value: Any) -> str:
    if isinstance(value, str):
        return value
    try:
        return json.dumps(value, ensure_ascii=False)
    except TypeError:
        return str(value)


def _normalize_field_name(field_name: str) -> str:
    field_name = str(field_name or "").strip()
    if len(field_name) <= MAX_FIELD_NAME_LENGTH:
        return field_name
    return field_name[:MAX_FIELD_NAME_LENGTH]


def _collect_json_template_fields(value: Any, prefix: str = "") -> List[Tuple[str, Any, str]]:
    fields: List[Tuple[str, Any, str]] = []

    if isinstance(value, dict):
        for key, child_value in value.items():
            key_text = str(key).strip()
            if not key_text:
                continue
            path = f"{prefix}.{key_text}" if prefix else key_text
            fields.append((path, child_value, path))
            fields.extend(_collect_json_template_fields(child_value, path))
        return fields

    if isinstance(value, list):
        if not value:
            return fields
        first_value = value[0]
        array_prefix = f"{prefix}[]" if prefix else ""
        if isinstance(first_value, dict):
            fields.extend(_collect_json_template_fields(first_value, array_prefix))
        elif isinstance(first_value, list):
            fields.append((array_prefix or "items[]", first_value, array_prefix or "items[]"))
            fields.extend(_collect_json_template_fields(first_value, array_prefix))
        elif prefix:
            fields.append((array_prefix, first_value, array_prefix))
        return fields

    return fields


async def parse_api_template_json_service(db: Session, data: ApiTemplateJsonParse):
    """解析JSON并生成API参数模板"""
    api = db.query(ApiInfo).filter(ApiInfo.api_id == data.api_id).first()
    if not api:
        return error_response(msg="解析失败，API不存在", data=None)

    json_text = (data.json_text or "").strip()
    if not json_text:
        return error_response(msg="解析失败，请输入JSON内容", data=None)

    try:
        parsed_json = json.loads(json_text)
    except json.JSONDecodeError as exc:
        return error_response(msg=f"解析失败，JSON格式错误：{exc.msg}", data=None)

    if not isinstance(parsed_json, (dict, list)):
        return error_response(msg="解析失败，JSON根节点必须是对象或数组", data=None)

    collected_fields = _collect_json_template_fields(parsed_json)
    seen_fields = set()
    template_payloads = []
    skipped_fields = []

    for raw_field_name, value, full_path in collected_fields:
        field_name = _normalize_field_name(raw_field_name)
        if not field_name or field_name in seen_fields:
            continue
        seen_fields.add(field_name)

        existing = await get_api_template_by_unique_fields(
            db,
            api_id=data.api_id,
            field_name=field_name
        )
        if existing:
            skipped_fields.append(field_name)
            continue

        remark = json.dumps({
            "source": "json_parse",
            "path": full_path,
            "sample": _json_sample(value)
        }, ensure_ascii=False)
        template_payloads.append(set_audit_fields_for_create({
            "field_name": field_name,
            "field_type": _json_value_type(value),
            "field_size": None,
            "default_value": _json_default_value(value),
            "is_required": "N",
            "is_unique": False,
            "api_id": data.api_id,
            "remark": remark,
            "creator": "json_parser"
        }))

    if not template_payloads and not skipped_fields:
        return error_response(msg="解析失败，未解析到可保存的字段", data=None)

    created_fields = []
    try:
        for payload in template_payloads:
            db_obj = ApiTemplate(**payload)
            db.add(db_obj)
            created_fields.append(payload["field_name"])
        db.commit()
    except Exception as exc:
        db.rollback()
        return error_response(msg="保存参数模板失败", data=None, error=str(exc))

    return success_response(
        msg=f"JSON解析完成，新增{len(created_fields)}个字段，跳过{len(skipped_fields)}个已存在字段",
        data={
            "created": len(created_fields),
            "skipped": len(skipped_fields),
            "createdFields": created_fields,
            "skippedFields": skipped_fields
        }
    )


async def get_api_template_service(db: Session, item_id: int):
    """获取接口模板详情"""
    obj = await get_api_template_by_id(db, item_id)
    if not obj:
        return error_response(
            msg="查询失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "接口模板不存在"}'
        )

    """将ORM对象转换为Schema对象"""
    schema_obj = ApiTemplateInfo.model_validate(obj)
    return success_response(msg="查询成功", data=schema_obj)


async def get_api_template_list_service(db: Session, data: ApiTemplateList):
    """获取接口模板分页列表（含关联信息）"""
    items, total = await get_api_template_list(db, data)

    """将字典转换为Schema对象"""
    schema_items = [ApiTemplateInfo.model_validate(item) for item in items]

    """构建分页响应"""
    page_data = create_page_response(
        items=schema_items,
        total=total,
        page_num=data.page_num,
        page_size=data.page_size
    )

    return success_response(msg="查询成功", data=page_data)


async def create_api_template_service(db: Session, data: ApiTemplateCreate):
    """创建接口模板"""
    """业务逻辑校验：检查是否存在相同的api_id和field_name组合"""
    existing = await get_api_template_by_unique_fields(
        db,
        api_id=data.api_id,
        field_name=data.field_name
    )

    if existing:
        return error_response(
            msg="添加失败，该字段已存在",
            data=existing,
            error=f'{"errorCode": "DUPLICATE_TEMPLATE", "message": "API ID为{data.api_id}的模板中，已存在名称为\'{data.field_name}\'的字段"}'
        )

    obj = await create_api_template(db, data.model_dump(by_alias=False))

    """将ORM对象转换为Schema对象"""
    schema_obj = ApiTemplateInfo.model_validate(obj)
    return success_response(msg="添加成功", data=schema_obj)


async def update_api_template_service(db: Session,  data: ApiTemplateUpdate):
    """更新接口模板"""
    """校验是否存在"""
    existing = await get_api_template_by_id(db, data.template_id)
    if not existing:
        return error_response(
            msg="更新失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "接口模板不存在"}'
        )

    obj = await update_api_template(db, data.template_id, data.model_dump(by_alias=False, exclude_unset=True))

    """将ORM对象转换为Schema对象"""
    schema_obj = ApiTemplateInfo.model_validate(obj)
    return success_response(msg="更新成功", data=schema_obj)


async def delete_api_template_service(db: Session, item_id: int):
    """删除接口模板"""
    """校验是否存在"""
    existing = await get_api_template_by_id(db, item_id)
    if not existing:
        return error_response(
            msg="删除失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "接口模板不存在"}'
        )

    obj = await delete_api_template(db, item_id)

    return success_response(
        msg="删除成功",
        data={"id": item_id, "message": "接口模板已删除"}
    )


async def delete_api_template_batch_service(db: Session, data: ApiTemplateBatchDelete):
    """批量删除接口参数模板"""
    ids = list(dict.fromkeys(data.ids or []))
    if not ids:
        return error_response(msg="批量删除失败，请选择要删除的参数模板", data=None)

    deleted_count = await delete_api_template_batch(db, ids)
    return success_response(
        msg=f"批量删除成功，已删除{deleted_count}条参数模板",
        data={"ids": ids, "deletedCount": deleted_count}
    )


async def export_api_templates_service(db: Session, api_id: int = None, format_type: str = "excel"):
    """导出API模板信息"""
    query = db.query(ApiTemplate)
    if api_id:
        query = query.filter(ApiTemplate.api_id == api_id)
    
    templates = query.all()
    
    """转换为 DataFrame"""
    data = []
    for t in templates:
        data.append({
            "template_id": t.template_id,
            "field_name": t.field_name,
            "field_type": t.field_type,
            "field_size": t.field_size,
            "default_value": t.default_value,
            "is_required": t.is_required,
            "api_id": t.api_id,
            "remark": t.remark
        })
    
    df = pd.DataFrame(data)
    
    if format_type == "csv":
        output = io.StringIO()
        df.to_csv(output, index=False, encoding='utf-8-sig')
        media_type = "text/csv"
        filename = "api_templates.csv"
        content = output.getvalue().encode('utf-8-sig')
    else:
        output = io.BytesIO()
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            df.to_excel(writer, index=False, sheet_name='Templates')
        media_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        filename = "api_templates.xlsx"
        content = output.getvalue()
        
    return StreamingResponse(
        iter([content]),
        media_type=media_type,
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
