"""
元素模板Service层
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from schemas.element_template_schemas import ElementTemplateCreate, ElementTemplateUpdate, ElementTemplateInfo
from mysql.element_template_sql import (
    get_element_template_by_id,
    get_element_template_by_unique_fields,
    get_element_template_list,
    create_element_template,
    update_element_template,
    delete_element_template
)
from utils.pagination import create_page_response
from core.responsemsg import success_response, error_response


async def get_element_template_service(db: Session, item_id: int):
    """获取元素模板详情"""
    obj = await get_element_template_by_id(db, item_id)
    if not obj:
        return error_response(
            msg="查询失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "元素模板不存在"}'
        )
    
    # 将ORM对象转换为Schema对象
    schema_obj = ElementTemplateInfo.model_validate(obj)
    return success_response(msg="查询成功", data=schema_obj)


async def get_element_template_list_service(db: Session, page_num: int = 1, page_size: int = 10):
    """获取元素模板分页列表"""
    items, total = await get_element_template_list(db, page_num, page_size)
    
    # 将ORM对象转换为Schema对象
    schema_items = [ElementTemplateInfo.model_validate(item) for item in items]
    
    # 构建分页响应
    page_data = create_page_response(
        items=schema_items,
        total=total,
        page_num=page_num,
        page_size=page_size
    )
    
    return success_response(msg="查询成功", data=page_data)


async def create_element_template_service(db: Session, data: ElementTemplateCreate):
    """创建元素模板"""
    # 业务逻辑校验：检查是否存在相同的element_name和element_type组合
    existing = await get_element_template_by_unique_fields(
        db, 
        element_name=data.element_name,
        element_type=data.element_type,
        page_id=data.page_id
    )
    
    if existing:
        return error_response(
            msg="添加失败，该元素已存在",
            data=existing,
            error=f'{{"errorCode": "DUPLICATE_ELEMENT", "message": "已存在名称为\'{data.element_name}\'且类型为{data.element_type}的元素模板"}}'
        )
    
    obj = await create_element_template(db, data.model_dump(by_alias=False))
    
    # 将ORM对象转换为Schema对象
    schema_obj = ElementTemplateInfo.model_validate(obj)
    return success_response(msg="添加成功", data=schema_obj)


async def update_element_template_service(db: Session, item_id: int, data: ElementTemplateUpdate):
    """更新元素模板"""
    # 校验是否存在
    existing = await get_element_template_by_id(db, item_id)
    if not existing:
        return error_response(
            msg="更新失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "元素模板不存在"}'
        )
    
    obj = await update_element_template(db, item_id, data.model_dump(by_alias=False, exclude_unset=True))
    
    return success_response(msg="更新成功", data=obj)


async def delete_element_template_service(db: Session, item_id: int):
    """删除元素模板"""
    # 校验是否存在
    existing = await get_element_template_by_id(db, item_id)
    if not existing:
        return error_response(
            msg="删除失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "元素模板不存在"}'
        )
    
    obj = await delete_element_template(db, item_id)
    
    return success_response(
        msg="删除成功",
        data={"id": item_id, "message": "元素模板已删除"}
    )
