"""
流程步骤Service层
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from schemas.flow_step_schemas import FlowStepCreate, FlowStepUpdate, FlowStepList, FlowStepInfo
from mysql.flow_step_sql import (
    get_flow_step_by_id,
    get_flow_step_by_unique_fields,
    get_flow_step_list,
    get_flow_steps_by_flow_id,
    create_flow_step,
    update_flow_step,
    delete_flow_step
)
from utils.pagination import create_page_response
from core.responsemsg import success_response, error_response


async def get_flow_step_service(db: Session, item_id: int):
    """获取流程步骤详情"""
    obj = await get_flow_step_by_id(db, item_id)
    if not obj:
        return error_response(
            msg="查询失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "流程步骤不存在"}'
        )
    
    # 将字典转换为Schema对象
    schema_obj = FlowStepInfo.model_validate(obj)
    return success_response(msg="查询成功", data=schema_obj)


async def get_flow_step_list_service(db: Session, filter_params: FlowStepList):
    """获取流程步骤分页列表"""
    items, total = await get_flow_step_list(db, filter_params)
    
    # 将字典转换为Schema对象
    schema_items = [FlowStepInfo.model_validate(item) for item in items]
    
    # 构建分页响应
    page_data = create_page_response(
        items=schema_items,
        total=total,
        page_num=filter_params.page_num,
        page_size=filter_params.page_size
    )
    
    return success_response(msg="查询成功", data=page_data)


async def get_flow_steps_by_flow_id_service(db: Session, flow_id: int):
    """根据流程ID获取所有步骤"""
    items = await get_flow_steps_by_flow_id(db, flow_id)
    
    # 将字典转换为Schema对象
    schema_items = [FlowStepInfo.model_validate(item) for item in items]
    
    return success_response(msg="查询成功", data=schema_items)


async def create_flow_step_service(db: Session, data: FlowStepCreate):
    """创建流程步骤"""
    obj = await create_flow_step(db, data.model_dump(by_alias=False))
    
    # 将ORM对象转换为Schema对象
    schema_obj = FlowStepInfo.model_validate(obj)
    return success_response(msg="添加成功", data=schema_obj)


async def update_flow_step_service(db: Session, data: FlowStepUpdate):
    """更新流程步骤"""
    # 校验是否存在
    existing = await get_flow_step_by_id(db, data.step_id)
    if not existing:
        return error_response(
            msg="更新失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "流程步骤不存在"}'
        )
    
    obj = await update_flow_step(db, data.step_id, data.model_dump(by_alias=False, exclude_unset=True))
    
    # 将ORM对象转换为Schema对象
    schema_obj = FlowStepInfo.model_validate(obj)
    return success_response(msg="更新成功", data=schema_obj)


async def delete_flow_step_service(db: Session, item_id: int):
    """删除流程步骤"""
    # 校验是否存在
    existing = await get_flow_step_by_id(db, item_id)
    if not existing:
        return error_response(
            msg="删除失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "流程步骤不存在"}'
        )
    
    obj = await delete_flow_step(db, item_id)
    
    return success_response(
        msg="删除成功",
        data={"id": item_id, "message": "流程步骤已删除"}
    )
