"""
流程步骤Service层
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from schemas.flow_step_schemas import FlowStepCreate, FlowStepUpdate, FlowStepInfo
from mysql.flow_step_sql import (
    get_flow_step_by_id,
    get_flow_step_by_unique_fields,
    get_flow_step_list,
    create_flow_step,
    update_flow_step,
    delete_flow_step
)
from utils.pagination import create_page_response
from core.responsemsg import success_response, error_response


async def get_flow_step_service(db: Session, item_id: int):
    """获取流程步骤详情"""
    obj = await get_flow_step_by_id(db, item_id)
    if not obj:
        return error_response(
            msg="查询失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "流程步骤不存在"}'
        )
    
    # 将ORM对象转换为Schema对象
    schema_obj = FlowStepInfo.model_validate(obj)
    return success_response(msg="查询成功", data=schema_obj)


async def get_flow_step_list_service(db: Session, page_num: int = 1, page_size: int = 10):
    """获取流程步骤分页列表"""
    items, total = await get_flow_step_list(db, page_num, page_size)
    
    # 将ORM对象转换为Schema对象
    schema_items = [FlowStepInfo.model_validate(item) for item in items]
    
    # 构建分页响应
    page_data = create_page_response(
        items=schema_items,
        total=total,
        page_num=page_num,
        page_size=page_size
    )
    
    return success_response(msg="查询成功", data=page_data)


async def create_flow_step_service(db: Session, data: FlowStepCreate):
    """创建流程步骤"""
    # 业务逻辑校验：检查是否存在相同的api_id和instance_id组合
    existing = await get_flow_step_by_unique_fields(
        db, 
        api_id=data.api_id,
        instance_id=data.instance_id
    )
    
    if existing:
        return error_response(
            msg="添加失败，该步骤已存在",
            data=existing,
            error=f'{{"errorCode": "DUPLICATE_STEP", "message": "接口ID为{data.api_id}、实例ID为{data.instance_id}的流程步骤已存在"}}'
        )
    
    obj = await create_flow_step(db, data.model_dump(by_alias=False))
    
    # 将ORM对象转换为Schema对象
    schema_obj = FlowStepInfo.model_validate(obj)
    return success_response(msg="添加成功", data=schema_obj)


async def update_flow_step_service(db: Session, item_id: int, data: FlowStepUpdate):
    """更新流程步骤"""
    # 校验是否存在
    existing = await get_flow_step_by_id(db, item_id)
    if not existing:
        return error_response(
            msg="更新失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "流程步骤不存在"}'
        )
    
    obj = await update_flow_step(db, item_id, data.model_dump(by_alias=False, exclude_unset=True))
    
    return success_response(msg="更新成功", data=obj)


async def delete_flow_step_service(db: Session, item_id: int):
    """删除流程步骤"""
    # 校验是否存在
    existing = await get_flow_step_by_id(db, item_id)
    if not existing:
        return error_response(
            msg="删除失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "流程步骤不存在"}'
        )
    
    obj = await delete_flow_step(db, item_id)
    
    return success_response(
        msg="删除成功",
        data={"id": item_id, "message": "流程步骤已删除"}
    )
