"""
页面信息Service层
Generated by scaffold script
"""
import os
from datetime import datetime
from sqlalchemy.orm import Session
from schemas.page_info_schemas import PageInfoCreate, PageInfoUpdate, PageInfoInfo
from mysql.page_info_sql import (
    get_page_info_by_id,
    get_page_info_by_unique_fields,
    get_page_info_list,
    create_page_info,
    update_page_info,
    delete_page_info
)
from mysql.page_instance_sql import (
    get_page_instances_by_page_ids,
    delete_page_instance_by_page_ids,
)
from mysql.page_result_sql import delete_page_result_by_instance_ids
from utils.pagination import create_page_response
from core.responsemsg import success_response, error_response


def _build_real_file_name(file_name: str | None) -> str | None:
    """真实文件名称 = 当前时间戳 + "_" + 文件名称"""
    if not file_name:
        return None
    return f"{datetime.now().strftime('%Y%m%d%H%M%S')}_{file_name}"


async def get_page_info_service(db: Session, item_id: int):
    """获取页面信息详情"""
    obj = await get_page_info_by_id(db, item_id)
    if not obj:
        return error_response(
            msg="查询失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "页面信息不存在"}'
        )

    # 将ORM对象转换为Schema对象
    schema_obj = PageInfoInfo.model_validate(obj)
    return success_response(msg="查询成功", data=schema_obj)


async def get_page_info_list_service(db: Session, page_num: int = 1, page_size: int = 10, project_id: int | None = None):
    """获取页面信息分页列表"""
    items, total = await get_page_info_list(db, page_num, page_size, project_id)

    # 将ORM对象转换为Schema对象
    schema_items = [PageInfoInfo.model_validate(item) for item in items]

    # 构建分页响应
    page_data = create_page_response(
        items=schema_items,
        total=total,
        page_num=page_num,
        page_size=page_size
    )

    return success_response(msg="查询成功", data=page_data)


async def create_page_info_service(db: Session, data: PageInfoCreate):
    """创建页面信息"""
    # 业务逻辑校验：检查是否存在相同的page_name和project_id组合
    existing = await get_page_info_by_unique_fields(
        db,
        page_name=data.page_name,
        project_id=data.project_id
    )

    if existing:
        schema_existing = PageInfoInfo.model_validate(existing)
        return error_response(
            msg="添加失败，该页面已存在",
            data=schema_existing,
            error=f'{{"errorCode": "DUPLICATE_PAGE", "message": "项目ID为{data.project_id}的页面中，已存在名称为\'{data.page_name}\'的页面"}}'
        )

    data_dict = data.model_dump(by_alias=False)
    # 真实文件名称 = 当前时间戳 + "_" + 文件名称
    data_dict["real_file_name"] = _build_real_file_name(data.file_name)

    obj = await create_page_info(db, data_dict)

    # 将ORM对象转换为Schema对象
    schema_obj = PageInfoInfo.model_validate(obj)
    return success_response(msg="添加成功", data=schema_obj)


async def update_page_info_service(db: Session, data: PageInfoUpdate):
    """更新页面信息"""
    # 校验是否存在
    existing = await get_page_info_by_id(db, data.page_id)
    if not existing:
        return error_response(
            msg="更新失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "页面信息不存在"}'
        )

    data_dict = data.model_dump(by_alias=False, exclude_unset=True)
    # 仅在本次更新带了文件名时，才刷新真实文件名称
    if data.file_name:
        data_dict["real_file_name"] = _build_real_file_name(data.file_name)

    obj = await update_page_info(db, data.page_id, data_dict)

    schema_obj = PageInfoInfo.model_validate(obj)
    return success_response(msg="更新成功", data=schema_obj)

async def delete_page_info_batch_service(db: Session, ids: list[int]):
    """批量删除页面信息（含关联子表与文件）"""
    # 删除关联表的信息（手动级联：page_instance -> page_result）
    await delete_page_related_data(db, ids)
    # 删除对应的playwright文件
    await delete_page_playwright_files(db, ids)
    # 批量删除页面信息
    obj = await delete_page_info(db, ids)
    if not obj:
        return error_response(
            msg="删除失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "页面信息不存在"}'
        )
    return success_response(msg="删除成功", data={"ids": ids, "message": "页面信息已删除"})


async def delete_page_related_data(db: Session, ids: list[int]):
    """删除页面信息关联的子表数据（page_instance 及其下的 page_result）"""
    if not ids:
        return
    # 先取出这些页面下的全部实例，拿到 instance_id 以清理 page_result
    instances = await get_page_instances_by_page_ids(db, ids)
    instance_ids = [i.page_instance_id for i in instances]
    # 先删子表 page_result，再删 page_instance
    await delete_page_result_by_instance_ids(db, instance_ids)
    await delete_page_instance_by_page_ids(db, ids)


async def delete_page_playwright_files(db: Session, ids: list[int]):
    """删除page_info对应的playwright生成的文件"""
    if not ids:
        return
    code_path = os.getenv("PLAYWRIGHT_CODE_PATH")
    if not code_path:
        return
    # 根据ids获取page_info记录，删除其real_file_name对应的文件
    for page_id in ids:
        page_info = await get_page_info_by_id(db, page_id)
        if not page_info or not page_info.real_file_name:
            continue
        file_path = os.path.join(code_path, page_info.real_file_name)
        try:
            if os.path.exists(file_path):
                os.remove(file_path)
        except OSError:
            # 文件删除失败不阻断数据库删除流程
            pass


async def delete_page_info_service(db: Session, item_id: int):
    """删除页面信息（含关联子表与文件）"""
    # 删除关联表的信息（手动级联）
    await delete_page_related_data(db, [item_id])
    # 删除对应的文件
    await delete_page_playwright_files(db, [item_id])
    # 删除页面信息
    obj = await delete_page_info(db, [item_id])
    if not obj:
        return error_response(
            msg="删除失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "页面信息不存在"}'
        )

    return success_response(
        msg="删除成功",
        data={"id": item_id, "message": "页面信息已删除"}
    )
