"""
页面实例Service层
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from schemas.page_instance_schemas import PageInstanceCreate, PageInstanceUpdate, PageInstanceInfo
from mysql.page_instance_sql import (
    get_page_instance_by_id,
    get_page_instance_by_unique_fields,
    get_page_instance_list,
    create_page_instance,
    update_page_instance,
    delete_page_instance
)
from utils.pagination import create_page_response
from core.responsemsg import success_response, error_response


async def get_page_instance_service(db: Session, item_id: int):
    """获取页面实例详情"""
    obj = await get_page_instance_by_id(db, item_id)
    if not obj:
        return error_response(
            msg="查询失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "页面实例不存在"}'
        )
    
    # 将ORM对象转换为Schema对象
    schema_obj = PageInstanceInfo.model_validate(obj)
    return success_response(msg="查询成功", data=schema_obj)


async def get_page_instance_list_service(db: Session, page_num: int = 1, page_size: int = 10):
    """获取页面实例分页列表"""
    items, total = await get_page_instance_list(db, page_num, page_size)
    
    # 将ORM对象转换为Schema对象
    schema_items = [PageInstanceInfo.model_validate(item) for item in items]
    
    # 构建分页响应
    page_data = create_page_response(
        items=schema_items,
        total=total,
        page_num=page_num,
        page_size=page_size
    )
    
    return success_response(msg="查询成功", data=page_data)


async def create_page_instance_service(db: Session, data: PageInstanceCreate):
    """创建页面实例"""
    # 业务逻辑校验：检查是否存在相同的instance_name和page_id组合
    existing = await get_page_instance_by_unique_fields(
        db, 
        instance_name=data.instance_name,
        page_id=data.page_id
    )
    
    if existing:
        return error_response(
            msg="添加失败，该实例已存在",
            data=existing,
            error=f'{{"errorCode": "DUPLICATE_INSTANCE", "message": "页面ID为{data.page_id}的实例中，已存在名称为\'{data.instance_name}\'的页面实例"}}'
        )
    
    obj = await create_page_instance(db, data.model_dump(by_alias=False))
    
    # 将ORM对象转换为Schema对象
    schema_obj = PageInstanceInfo.model_validate(obj)
    return success_response(msg="添加成功", data=schema_obj)


async def update_page_instance_service(db: Session, item_id: int, data: PageInstanceUpdate):
    """更新页面实例"""
    # 校验是否存在
    existing = await get_page_instance_by_id(db, item_id)
    if not existing:
        return error_response(
            msg="更新失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "页面实例不存在"}'
        )
    
    obj = await update_page_instance(db, item_id, data.model_dump(by_alias=False, exclude_unset=True))
    
    return success_response(msg="更新成功", data=obj)


async def delete_page_instance_service(db: Session, item_id: int):
    """删除页面实例"""
    # 校验是否存在
    existing = await get_page_instance_by_id(db, item_id)
    if not existing:
        return error_response(
            msg="删除失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "页面实例不存在"}'
        )
    
    obj = await delete_page_instance(db, item_id)
    
    return success_response(
        msg="删除成功",
        data={"id": item_id, "message": "页面实例已删除"}
    )
