"""
页面信息Service层
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from schemas.page_info_schemas import PageInfoCreate, PageInfoUpdate, PageInfoInfo
from mysql.page_info_sql import (
    get_page_info_by_id,
    get_page_info_by_unique_fields,
    get_page_info_list,
    create_page_info,
    update_page_info,
    delete_page_info
)
from utils.pagination import create_page_response
from core.responsemsg import success_response, error_response


async def get_page_info_service(db: Session, item_id: int):
    """获取页面信息详情"""
    obj = await get_page_info_by_id(db, item_id)
    if not obj:
        return error_response(
            msg="查询失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "页面信息不存在"}'
        )
    
    # 将ORM对象转换为Schema对象
    schema_obj = PageInfoInfo.model_validate(obj)
    return success_response(msg="查询成功", data=schema_obj)


async def get_page_info_list_service(db: Session, page_num: int = 1, page_size: int = 10):
    """获取页面信息分页列表"""
    items, total = await get_page_info_list(db, page_num, page_size)
    
    # 将ORM对象转换为Schema对象
    schema_items = [PageInfoInfo.model_validate(item) for item in items]
    
    # 构建分页响应
    page_data = create_page_response(
        items=schema_items,
        total=total,
        page_num=page_num,
        page_size=page_size
    )
    
    return success_response(msg="查询成功", data=page_data)


async def create_page_info_service(db: Session, data: PageInfoCreate):
    """创建页面信息"""
    # 业务逻辑校验：检查是否存在相同的page_name和project_id组合
    existing = await get_page_info_by_unique_fields(
        db, 
        page_name=data.page_name,
        project_id=data.project_id
    )
    
    if existing:
        return error_response(
            msg="添加失败，该页面已存在",
            data=existing,
            error=f'{{"errorCode": "DUPLICATE_PAGE", "message": "项目ID为{data.project_id}的页面中，已存在名称为\'{data.page_name}\'的页面"}}'
        )
    
    obj = await create_page_info(db, data.model_dump(by_alias=False))
    
    # 将ORM对象转换为Schema对象
    schema_obj = PageInfoInfo.model_validate(obj)
    return success_response(msg="添加成功", data=schema_obj)


async def update_page_info_service(db: Session, item_id: int, data: PageInfoUpdate):
    """更新页面信息"""
    # 校验是否存在
    existing = await get_page_info_by_id(db, item_id)
    if not existing:
        return error_response(
            msg="更新失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "页面信息不存在"}'
        )
    
    obj = await update_page_info(db, item_id, data.model_dump(by_alias=False, exclude_unset=True))
    
    return success_response(msg="更新成功", data=obj)


async def delete_page_info_service(db: Session, item_id: int):
    """删除页面信息"""
    # 校验是否存在
    existing = await get_page_info_by_id(db, item_id)
    if not existing:
        return error_response(
            msg="删除失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "页面信息不存在"}'
        )
    
    obj = await delete_page_info(db, item_id)
    
    return success_response(
        msg="删除成功",
        data={"id": item_id, "message": "页面信息已删除"}
    )
