"""
系统用户Service层
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from schemas.sys_user_schemas import SysUserCreate, SysUserUpdate, SysUserInfo
from mysql.sys_user_sql import (
    get_sys_user_by_id,
    get_sys_user_by_username,
    get_sys_user_list,
    create_sys_user,
    update_sys_user,
    delete_sys_user
)
from utils.pagination import create_page_response
from core.responsemsg import success_response, error_response
from core.logger import logger


async def get_sys_user_service(db: Session, item_id: int):
    """获取系统用户详情"""
    obj = await get_sys_user_by_id(db, item_id)
    if not obj:
        return error_response(
            msg="查询失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "系统用户不存在"}'
        )
    
    """将ORM对象转换为Schema对象"""
    schema_obj = SysUserInfo.model_validate(obj)
    return success_response(msg="查询成功", data=schema_obj)


async def get_sys_user_list_service(db: Session, page_num: int = 1, page_size: int = 10):
    """获取系统用户分页列表"""
    items, total = await get_sys_user_list(db, page_num, page_size)
    
    """将ORM对象转换为Schema对象"""
    schema_items = [SysUserInfo.model_validate(item) for item in items]
    
    """构建分页响应"""
    page_data = create_page_response(
        items=schema_items,
        total=total,
        page_num=page_num,
        page_size=page_size
    )
    
    return success_response(msg="查询成功", data=page_data)


async def create_sys_user_service(db: Session, data: SysUserCreate):
    """创建系统用户"""
    """业务逻辑校验：检查是否存在相同的username"""
    existing = await get_sys_user_by_username(
        db, 
        username=data.username
    )
    
    if existing:
        return error_response(
            msg="添加失败，该用户已存在",
            data=SysUserInfo.model_validate(existing),
            error=f'{{"errorCode": "DUPLICATE_USER", "message": "已存在用户名为\'{data.username}\'的用户"}}'
        )
    
    obj = await create_sys_user(db, data.model_dump(by_alias=False))
    
    """将ORM对象转换为Schema对象"""
    schema_obj = SysUserInfo.model_validate(obj)
    return success_response(msg="添加成功", data=schema_obj)


async def update_sys_user_service(db: Session, item_id: int, data: SysUserUpdate):
    """更新系统用户"""
    """校验是否存在"""
    existing = await get_sys_user_by_id(db, item_id)
    if not existing:
        return error_response(
            msg="更新失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "系统用户不存在"}'
        )
    """校验更新后的用户名是否已被其他用户使用"""
    existing = await get_sys_user_by_username(
        db, 
        username=data.username
    )
    
    if existing and existing.user_id != item_id:
        return error_response(
            msg="更新失败，该用户已存在",
            data=SysUserInfo.model_validate(existing),
            error=f'{{"errorCode": "DUPLICATE_USER", "message": "已存在用户名为\'{data.username}\'的用户"}}'
        )
    
    obj = await update_sys_user(db, item_id, data.model_dump(by_alias=False, exclude_unset=True))
    
    """将ORM对象转换为Schema对象"""
    schema_obj = SysUserInfo.model_validate(obj)
    return success_response(msg="更新成功", data=schema_obj)

async def delete_sys_user_batch_service(db: Session, ids: list[int]):
    """批量删除系统用户"""
   
    obj = await delete_sys_user(db, ids)         
    
    if not obj:
        return error_response(
            msg="删除失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "没有找到要删除的系统用户"}'
        )
    
    return success_response(
        msg="删除成功",
        data={"deleted_ids": ids, "message": f"成功删除{obj}个系统用户"}
    )

async def delete_sys_user_service(db: Session, item_id: int):
    """删除系统用户"""  
    obj = await delete_sys_user(db, [item_id])
    if not obj:
        return error_response(
            msg="删除失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "没有找到要删除的系统用户"}'
        )
    return success_response(
        msg="删除成功",
        data={"id": item_id, "message": "系统用户已删除"}
    )
