"""
Token信息Service层
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from schemas.token_info_schemas import TokenInfoCreate, TokenInfoList, TokenInfoUpdate, TokenInfoInfo
from mysql.token_info_sql import (
    get_token_info_by_id,
    get_token_info_by_unique_fields,
    get_token_info_list,
    create_token_info,
    update_token_info,
    delete_token_info
)
from utils.pagination import create_page_response
from core.responsemsg import success_response, error_response


async def get_token_info_service(db: Session, item_id: int):
    """获取Token信息详情"""
    obj = await get_token_info_by_id(db, item_id)
    if not obj:
        return error_response(
            msg="查询失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "Token信息不存在"}'
        )
    
    # 将ORM对象转换为Schema对象
    schema_obj = TokenInfoInfo.model_validate(obj)
    return success_response(msg="查询成功", data=schema_obj)


async def get_token_info_list_service(db: Session, filter: TokenInfoList):
    """获取Token信息分页列表"""
    items, total = await get_token_info_list(db, filter = filter)
    
    # 将字典转换为Schema对象
    schema_items = [TokenInfoInfo.model_validate(item) for item in items]
    
    # 构建分页响应
    page_data = create_page_response(
        items=schema_items,
        total=total,
        page_num=filter.page_num,
        page_size=filter.page_size
    )
    
    return success_response(msg="查询成功", data=page_data)


async def create_token_info_service(db: Session, data: TokenInfoCreate):
    """创建Token信息"""
    # 业务逻辑校验：检查是否存在相同的project_id和name组合
    existing = await get_token_info_by_unique_fields(
        db, 
        project_id=data.project_id,
        name=data.name
    )
    
    if existing:
        # 将ORM对象转换为Schema对象
        schema_existing = TokenInfoInfo.model_validate(existing)
        return error_response(
            msg="添加失败，该Token已存在",
            data=schema_existing,
            error=f'{{"errorCode": "DUPLICATE_TOKEN", "message": "项目ID为{data.project_id}的Token中，已存在名称为\'{data.name}\'的Token"}}'
        )
    
    obj = await create_token_info(db, data.model_dump(by_alias=False))
    
    # 将ORM对象转换为Schema对象
    schema_obj = TokenInfoInfo.model_validate(obj)
    return success_response(msg="添加成功", data=schema_obj)


async def update_token_info_service(db: Session,  data: TokenInfoUpdate):
    """更新Token信息"""
    # 校验是否存在
    existing = await get_token_info_by_id(db, data.token_id)
    if not existing:
        return error_response(
            msg="更新失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "Token信息不存在"}'
        )
    
    obj = await update_token_info(db, data.token_id, data.model_dump(by_alias=False, exclude_unset=True))
    
    # 将ORM对象转换为Schema对象
    schema_obj = TokenInfoInfo.model_validate(obj)
    return success_response(msg="更新成功", data=schema_obj)


async def delete_token_info_service(db: Session, item_id: int):
    """删除Token信息"""
    # 校验是否存在
    existing = await get_token_info_by_id(db, item_id)
    if not existing:
        return error_response(
            msg="删除失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "Token信息不存在"}'
        )
    
    obj = await delete_token_info(db, item_id)
    
    return success_response(
        msg="删除成功",
        data={"id": item_id, "message": "Token信息已删除"}
    )
