"""
Token信息Service层
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from schemas.token_info_schemas import TokenInfoCreate, TokenInfoList, TokenInfoUpdate, TokenInfoInfo
from mysql.token_info_sql import (
    get_token_info_by_id,
    get_token_info_by_unique_fields,
    get_token_info_list,
    create_token_info,
    update_token_info,
    delete_token_info,
    delete_token_info_batch
)
from mysql.api_result_sql import get_latest_result_by_instance_id
from service.api_execute_service import execute_api_service
from service.page_execute_service import save_token_json_by_instance
from schemas.api_execute_schemas import ApiExecuteRequest
from utils.pagination import create_page_response
from core.responsemsg import success_response, error_response
import json
from core.logger import logger


async def _prepare_token_payload(db: Session, data: TokenInfoCreate | TokenInfoUpdate) -> dict:
    """根据来源整理入库数据。web 来源会先执行页面实例并保存 token JSON。"""
    payload = data.model_dump(by_alias=False, exclude_unset=True)
    token_type = payload.get("token_type", getattr(data, "token_type", 1)) or 1

    if token_type == 2:
        instance_id = payload.get("instance_id", getattr(data, "instance_id", None))
        if not instance_id:
            raise ValueError("web来源Token必须选择页面实例")

        token_file_name = payload.get("token") or getattr(data, "token", None)
        save_result = await save_token_json_by_instance(
            db=db,
            page_instance_id=instance_id,
            token_file_name=token_file_name,
        )
        if not save_result.get("success"):
            error_msg = save_result.get("msg") or "保存token json失败"
            detail = save_result.get("data") or save_result.get("error")
            if detail:
                error_msg = f"{error_msg}：{detail}"
            raise ValueError(error_msg)
        payload["token"] = save_result.get("data", {}).get("tokenFileName")

    return payload


async def get_token_info_service(db: Session, item_id: int):
    """获取Token信息详情"""
    obj = await get_token_info_by_id(db, item_id)
    if not obj:
        return error_response(
            msg="查询失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "Token信息不存在"}'
        )
    
    # 将ORM对象转换为Schema对象
    schema_obj = TokenInfoInfo.model_validate(obj)
    return success_response(msg="查询成功", data=schema_obj)


async def get_token_info_list_service(db: Session, filter: TokenInfoList):
    """获取Token信息分页列表"""
    items, total = await get_token_info_list(db, filter = filter)
    
    # 将字典转换为Schema对象
    schema_items = [TokenInfoInfo.model_validate(item) for item in items]
    
    # 构建分页响应
    page_data = create_page_response(
        items=schema_items,
        total=total,
        page_num=filter.page_num,
        page_size=filter.page_size
    )
    
    return success_response(msg="查询成功", data=page_data)


async def create_token_info_service(db: Session, data: TokenInfoCreate):
    """创建Token信息"""
    # 业务逻辑校验：检查是否存在相同的project_id和name组合
    existing = await get_token_info_by_unique_fields(
        db, 
        project_id=data.project_id,
        name=data.name
    )
    
    if existing:
        # 将ORM对象转换为Schema对象
        schema_existing = TokenInfoInfo.model_validate(existing)
        return error_response(
            msg="添加失败，该Token已存在",
            data=schema_existing,
            error=f'{{"errorCode": "DUPLICATE_TOKEN", "message": "项目ID为{data.project_id}的Token中，已存在名称为\'{data.name}\'的Token"}}'
        )
    
    try:
        data_dict = await _prepare_token_payload(db, data)
    except Exception as e:
        return error_response(
            msg=f"添加失败：{str(e)}",
            data=None,
            error=f'{{"errorCode": "SAVE_TOKEN_ERROR", "message": "{str(e)}"}}'
        )

    obj = await create_token_info(db, data_dict)
    
    # 将ORM对象转换为Schema对象
    schema_obj = TokenInfoInfo.model_validate(obj)
    return success_response(msg="添加成功", data=schema_obj)


async def update_token_info_service(db: Session,  data: TokenInfoUpdate):
    """更新Token信息"""
    # 校验是否存在
    existing = await get_token_info_by_id(db, data.token_id)
    if not existing:
        return error_response(
            msg="更新失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "Token信息不存在"}'
        )
    
    try:
        data_dict = await _prepare_token_payload(db, data)
    except Exception as e:
        return error_response(
            msg=f"更新失败：{str(e)}",
            data=None,
            error=f'{{"errorCode": "SAVE_TOKEN_ERROR", "message": "{str(e)}"}}'
        )

    obj = await update_token_info(db, data.token_id, data_dict)
    
    # 将ORM对象转换为Schema对象
    schema_obj = TokenInfoInfo.model_validate(obj)
    return success_response(msg="更新成功", data=schema_obj)


async def delete_token_info_service(db: Session, item_id: int):
    """删除Token信息"""
    # 校验是否存在
    existing = await get_token_info_by_id(db, item_id)
    if not existing:
        return error_response(
            msg="删除失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "Token信息不存在"}'
        )
    
    obj = await delete_token_info(db, item_id)
    
    return success_response(
        msg="删除成功",
        data={"id": item_id, "message": "Token信息已删除"}
    )


async def delete_token_info_batch_service(db: Session, ids: list[int]):
    """批量删除Token信息"""
    deleted = await delete_token_info_batch(db, ids)
    if not deleted:
        return error_response(
            msg="批量删除失败，信息不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "Token信息不存在"}'
        )
    return success_response(msg="批量删除成功", data={"ids": ids, "deleted": deleted})


async def refresh_token_service(db: Session, token_id: int):
    """刷新Token
    
    Args:
        db: 数据库会话
        token_id: Token ID
        
    Returns:
        刷新结果
    """
    # 1. 获取Token信息
    token_info = await get_token_info_by_id(db, token_id)
    if not token_info:
        return error_response(
            msg="刷新失败，Token不存在",
            data=None,
            error='{"errorCode": "NOT_FOUND", "message": "Token不存在"}'
        )
    logger.info(f"刷新Token：获取到Token信息，token_id={token_id}, instance_id={token_info.instance_id}")
    
    # 2. 检查instance_id是否存在
    instance_id = token_info.instance_id
    if not instance_id:
        return error_response(
            msg="刷新失败，Token未关联实例",
            data=None,
            error='{"errorCode": "INVALID_INSTANCE", "message": "Token未关联实例ID"}'
        )
    
    try:
        if token_info.token_type == 2:
            save_result = await save_token_json_by_instance(
                db=db,
                page_instance_id=instance_id,
                token_file_name=token_info.token,
            )
            if not save_result.get("success"):
                return save_result

            token_file_name = save_result.get("data", {}).get("tokenFileName")
            await update_token_info(db, token_id, {"token": token_file_name})
            return success_response(
                msg="Token刷新成功",
                data={
                    "token_id": token_id,
                    "token": token_file_name,
                    "token_type": token_info.token_type
                }
            )

        # 3. 调用API执行服务，重新执行该实例
        execute_request = ApiExecuteRequest(execution_type=1, target_id=instance_id)
        execute_result = await execute_api_service(db, execute_request)
        
        # 4. 获取最新的执行结果
        latest_result = await get_latest_result_by_instance_id(db, instance_id)
        if not latest_result or not latest_result.response_info:
            return error_response(
                msg="刷新失败，未获取到执行结果",
                data=None,
                error='{"errorCode": "NO_RESULT", "message": "未获取到API执行结果"}'
            )
        
        # 5. 解析responseInfo，提取token
        response_info = latest_result.response_info
        if isinstance(response_info, str):
            try:
                response_data = json.loads(response_info)
            except json.JSONDecodeError:
                return error_response(
                    msg="刷新失败，响应格式错误",
                    data=None,
                    error='{"errorCode": "PARSE_ERROR", "message": "无法解析响应数据"}'
                )
        else:
            response_data = response_info
        
        # 6. 从响应中提取token（假设token在response_data的"token"或"data.token"字段中）
        extracted_token = None
        if isinstance(response_data, dict):
            # 尝试直接获取token
            extracted_token = response_data.get('token')
            # 如果没有，尝试从data中获取
            if not extracted_token and 'data' in response_data:
                data_obj = response_data['data']
                if isinstance(data_obj, dict):
                    extracted_token = data_obj.get('token')
        
        if not extracted_token:
            return error_response(
                msg="刷新失败，响应中未找到token字段",
                data=None,
                error='{"errorCode": "TOKEN_NOT_FOUND", "message": "响应数据中未包含token字段"}'
            )
        
        # 7. 拼接token：token类型 + 空格 + 返回的token
        token_type = token_info.type  # 假设type字段存储的是token类型，如"Bearer"
        token_map = {
            1: "Bearer",    
            2: "Basic",
            3: "JWT"
        }
        token_type = token_map.get(token_info.type, "Bearer")
        
        new_token = f"{token_type} {extracted_token}"
        
        # 8. 更新Token表中的token字段
        await update_token_info(db, token_id, {'token': new_token})
        
        return success_response(
            msg="Token刷新成功",
            data={
                "token_id": token_id,
                "new_token": new_token,
                "token_type": token_type
            }
        )
        
    except Exception as e:
        return error_response(
            msg=f"刷新失败：{str(e)}",
            data=None,
            error=f'{{"errorCode": "REFRESH_ERROR", "message": "{str(e)}"}}'
        )
