"""
参数实例CRUD操作
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from sqlalchemy import and_, func, select
from models.api_instance_model import ApiInstance
from typing import List, Optional, Tuple
from utils.data_paser import set_audit_fields_for_create, set_audit_fields_for_update
from schemas.api_instance_schemas import ApiInstanceList
from models.api_info_model import ApiInfo

async def get_api_instance_by_id(db: Session, instance_id: int) -> Optional[ApiInstance]:
    """根据ID获取参数实例"""
    return db.query(ApiInstance).filter(ApiInstance.instance_id == instance_id).first()


async def get_api_instance_by_unique_fields(
    db: Session,
    api_id: int,
    instance_name: str
) -> Optional[ApiInstance]:
    """根据唯一字段组合获取参数实例

    Args:
        db: 数据库会话
        api_id: API ID
        instance_name: 实例名称

    Returns:
        Optional[ApiInstance]: 如果存在则返回API实例，否则返回None
    """
    return db.query(ApiInstance).filter(
        and_(
            ApiInstance.api_id == api_id,
            ApiInstance.instance_name == instance_name
        )
    ).first()


async def get_api_instance_list(
    db: Session,
    data: ApiInstanceList
) -> Tuple[List[ApiInstance], int]:
    """获取参数实例列表（分页）

    Args:
        db: 数据库会话
        page_num: 页码，从1开始
        page_size: 每页大小

    Returns:
        Tuple[List[ApiInstance], int]: 数据列表和总记录数
    """
    # 计算偏移量
    offset = (data.page_num - 1) * data.page_size

    # 查询总记录数
    count_stmt = select(func.count()).select_from(ApiInstance).filter(*data.filter_params())
    total = db.execute(count_stmt).scalar()

    # 查询分页数据
    items = db.query(ApiInstance).filter(*data.filter_params()).order_by(ApiInstance.instance_id.desc()).offset(offset).limit(data.page_size).all()

    return items, total


async def get_api_instance_list_by_api_id(
    db: Session,
    api_id: int
) -> List[ApiInstance]:
    """根据API ID获取参数实例列表

    Args:
        db: 数据库会话
        api_id: API ID

    Returns:
        List[ApiInstance]: API实例列表
    """
    # 查询所有符合条件的数据
    items = db.query(ApiInstance).filter(
        ApiInstance.api_id == api_id
    ).all()

    return items


async def create_api_instance(db: Session, data: dict) -> ApiInstance:
    """创建参数实例

    Args:
        db: 数据库会话
        data: 参数实例数据字典

    Returns:
        ApiInstance: 创建的参数实例对象
    """
    # 自动设置审计字段（创建时间、更新时间）
    data = set_audit_fields_for_create(data)
    db_obj = ApiInstance(**data)
    db.add(db_obj)
    db.commit()
    db.refresh(db_obj)
    return db_obj


async def update_api_instance(db: Session, instance_id: int, data: dict) -> Optional[ApiInstance]:
    """更新参数实例

    Args:
        db: 数据库会话
        instance_id: 实例ID
        data: 更新的字段数据字典

    Returns:
        Optional[ApiInstance]: 更新后的参数实例对象，如果不存在则返回None
    """
    db_obj = db.query(ApiInstance).filter(ApiInstance.instance_id == instance_id).first()
    if db_obj:
        # 自动设置更新时间
        data = set_audit_fields_for_update(data)
        for key, value in data.items():
            setattr(db_obj, key, value)
        db.commit()
        db.refresh(db_obj)
    return db_obj


async def delete_api_instance(db: Session, instance_id: int) -> Optional[ApiInstance]:
    """删除参数实例

    Args:
        db: 数据库会话
        instance_id: 实例ID

    Returns:
        Optional[ApiInstance]: 被删除的参数实例对象，如果不存在则返回None
    """
    db_obj = db.query(ApiInstance).filter(ApiInstance.instance_id == instance_id).first()
    if db_obj:
        db.delete(db_obj)
        db.commit()
    return db_obj


async def delete_api_instance_by_api_id(db: Session, api_id: int):
    """根据API ID批量删除实例"""
    db.query(ApiInstance).filter(ApiInstance.api_id == api_id).delete(synchronize_session=False)
    db.commit()
