"""
参数实例CRUD操作
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from sqlalchemy import and_, func, select
from models.api_instance_model import ApiInstance
from typing import List, Optional, Tuple
from utils.data_paser import set_audit_fields_for_create, set_audit_fields_for_update
from schemas.api_instance_schemas import ApiInstanceList
from models.api_info_model import ApiInfo
from models.project_info_model import ProjectInfo

async def get_api_instance_by_id(db: Session, instance_id: int) -> Optional[dict]:
    """根据ID获取参数实例"""
    item = db.query(
                ApiInstance,
                ApiInfo.api_name,
                ProjectInfo.project_name,
                ProjectInfo.project_id,
                ApiInfo.method_url,
                ApiInfo.method_type,
                ProjectInfo.project_address       
            ).join(
                ApiInfo,ApiInfo.api_id == ApiInstance.api_id
            ).join(
                ProjectInfo,ProjectInfo.project_id == ApiInfo.project_id
            ).filter(ApiInstance.instance_id == instance_id).first()
    if item:
        return get_api_instance_detail_dict(item)

def get_api_instance_detail_dict(api_instance_tuple) -> dict:
    """将查询结果元组转换为字典"""
    ApiInstance, api_name, project_name, project_id, method_url, method_type, project_address = api_instance_tuple
    return {
        "instance_id": ApiInstance.instance_id,
        "api_id": ApiInstance.api_id,
        "instance_name": ApiInstance.instance_name,
        "instance_json": ApiInstance.instance_json,
        "create_time": ApiInstance.create_time,
        "update_time": ApiInstance.update_time,
        "description": ApiInstance.description,
        "remark": ApiInstance.remark,
        "status": ApiInstance.status,
        "exec_count": ApiInstance.exec_count,
        "expect_result": ApiInstance.expect_result,
        "api_name": api_name,
        "project_name": project_name,
        "project_id": project_id,
        "method_url": method_url,
        "method_type": method_type,
        "project_address": project_address
    }

async def get_api_instance_by_unique_fields(
    db: Session,
    api_id: int,
    instance_name: str
) -> Optional[ApiInstance]:
    """根据唯一字段组合获取参数实例

    Args:
        db: 数据库会话
        api_id: API ID
        instance_name: 实例名称

    Returns:
        Optional[ApiInstance]: 如果存在则返回API实例，否则返回None
    """
    return db.query(ApiInstance).filter(
        and_(
            ApiInstance.api_id == api_id,
            ApiInstance.instance_name == instance_name
        )
    ).first()

async def get_api_instance_count(db: Session,data: ApiInstanceList) -> int:
    """获取参数实例总记录数"""
    count_stmt = select(func.count()).select_from(ApiInstance).join(
                ApiInfo,ApiInfo.api_id == ApiInstance.api_id
            ).join(
                ProjectInfo,ProjectInfo.project_id == ApiInfo.project_id
            ).filter(*data.filter_params())
    total = db.execute(count_stmt).scalar()
    return total

async def get_api_instance_list(
    db: Session,
    data: ApiInstanceList
) -> Tuple[List[dict], int]:
    """获取参数实例列表（分页）

    Args:
        db: 数据库会话
        page_num: 页码，从1开始
        page_size: 每页大小

    Returns:
        Tuple[List[dict], int]: 数据列表和总记录数
    """
    """计算偏移量"""
    offset = (data.page_num - 1) * data.page_size

    """查询总记录数"""
    total = await get_api_instance_count(db, data)

    """查询分页数据"""
    items = db.query(
                ApiInstance,
                ApiInfo.api_name,
                ProjectInfo.project_name,
                ProjectInfo.project_id,
                ApiInfo.method_url,
                ApiInfo.method_type,
                ProjectInfo.project_address       
            ).join(
                ApiInfo,ApiInfo.api_id == ApiInstance.api_id
            ).join(
                ProjectInfo,ProjectInfo.project_id == ApiInfo.project_id
            ).filter(*data.filter_params()).order_by(ApiInstance.instance_id.desc()).offset(offset).limit(data.page_size).all()
    result_list = []
    for item in items:
        result_dict = get_api_instance_detail_dict(item)
        result_list.append(result_dict)

    return result_list, total


async def get_api_instance_list_by_api_id(
    db: Session,
    api_id: int
) -> List[ApiInstance]:
    """根据API ID获取参数实例列表

    Args:
        db: 数据库会话
        api_id: API ID

    Returns:
        List[ApiInstance]: API实例列表
    """
    """查询所有符合条件的数据"""
    items = db.query(ApiInstance).filter(
        ApiInstance.api_id == api_id
    ).all()

    return items


async def create_api_instance(db: Session, data: dict) -> ApiInstance:
    """创建参数实例

    Args:
        db: 数据库会话
        data: 参数实例数据字典

    Returns:
        ApiInstance: 创建的参数实例对象
    """
    """自动设置审计字段（创建时间、更新时间）"""
    data = set_audit_fields_for_create(data)
    db_obj = ApiInstance(**data)
    db.add(db_obj)
    db.commit()
    db.refresh(db_obj)
    return db_obj


async def update_api_instance(db: Session, instance_id: int, data: dict) -> Optional[ApiInstance]:
    """更新参数实例

    Args:
        db: 数据库会话
        instance_id: 实例ID
        data: 更新的字段数据字典

    Returns:
        Optional[ApiInstance]: 更新后的参数实例对象，如果不存在则返回None
    """
    db_obj = db.query(ApiInstance).filter(ApiInstance.instance_id == instance_id).first()
    if db_obj:
        """自动设置更新时间"""
        data = set_audit_fields_for_update(data)
        for key, value in data.items():
            setattr(db_obj, key, value)
        db.commit()
        db.refresh(db_obj)
    return db_obj


async def delete_api_instance(db: Session, instance_id: int) -> Optional[ApiInstance]:
    """删除参数实例

    Args:
        db: 数据库会话
        instance_id: 实例ID

    Returns:
        Optional[ApiInstance]: 被删除的参数实例对象，如果不存在则返回None
    """
    db_obj = db.query(ApiInstance).filter(ApiInstance.instance_id == instance_id).first()
    if db_obj:
        db.delete(db_obj)
        db.commit()
    return db_obj


async def delete_api_instance_by_api_id(db: Session, api_id: int):
    """根据API ID批量删除实例"""
    db.query(ApiInstance).filter(ApiInstance.api_id == api_id).delete(synchronize_session=False)
    db.commit()
