"""
接口信息CRUD操作
Generated by scaffold script
"""
from pydantic.types import T
from sqlalchemy.orm import Session
from sqlalchemy import and_, func, select
from models.api_info_model import ApiInfo
from models.project_info_model import ProjectInfo
from models.token_info_model import TokenInfo
from typing import List, Optional, Tuple
from schemas.api_info_schemas import ApiInfoInfo, ApiInfoList
from utils.data_paser import set_audit_fields_for_create, set_audit_fields_for_update


async def get_api_info_by_id(db: Session, api_id: int) -> Optional[ApiInfo]:
    """根据ID获取接口信息（含关联项目与Token信息）"""
    item = db.query(
            ApiInfo, 
            ProjectInfo.project_name, 
            ProjectInfo.project_address, 
            TokenInfo.name.label('token_name'), 
            TokenInfo.token
        ).outerjoin(
            ProjectInfo, ApiInfo.project_id == ProjectInfo.project_id
        ).outerjoin(
            TokenInfo, ApiInfo.token_id == TokenInfo.token_id
        ).filter(ApiInfo.api_id == api_id).first()
    
    if not item:
        return None
        
    api_info = item[0]
    result = ApiInfoInfo(
        api_id=api_info.api_id,
        api_name=api_info.api_name,
        method_type=api_info.method_type,
        method_url=api_info.method_url,
        project_id=api_info.project_id,
        token_id=api_info.token_id,
        request_header=api_info.request_header,
        params_path=api_info.params_path,
        description=api_info.description,
        creator=api_info.creator,
        remark=api_info.remark,
        create_time=api_info.create_time,
        update_time=api_info.update_time,
        project_name=item[1],
        project_address=item[2],
        token_name=item[3],
        token=item[4]
    )
    return result

async def get_api_info_by_unique_fields(
    db: Session, 
    method_url: str, 
    method_type: int, 
    project_id: int
) -> Optional[ApiInfo]:
    """根据唯一字段组合获取接口信息
    
    Args:
        db: 数据库会话
        method_url: 方法URL
        method_type: 方法类型
        project_id: 项目ID
        
    Returns:
        Optional[ApiInfo]: 如果存在则返回API信息，否则返回None
    """
    return db.query(ApiInfo).filter(
        and_(
            ApiInfo.method_url == method_url,
            ApiInfo.method_type == method_type,
            ApiInfo.project_id == project_id
        )
    ).first()


async def get_api_info_list(
    db: Session, 
    data: ApiInfoList
) -> Tuple[List[dict], int]:
    """获取接口信息分页列表（包含项目名称、项目地址、Token名称、Token值）
    
    Args:
        db: 数据库会话
        page_num: 页码，默认1
        page_size: 每页数量，默认10
        
    Returns:
        Tuple[List[dict], int]: (数据列表, 总记录数)
    """
    # 计算偏移量
    offset = (data.page_num - 1) * data.page_size
    
    # 查询总数
    count_stmt = select(func.count()).select_from(ApiInfo).outerjoin(
        ProjectInfo, ApiInfo.project_id == ProjectInfo.project_id
    ).outerjoin(
        TokenInfo, ApiInfo.token_id == TokenInfo.token_id
    ).where(*data.filter_params())
    total = db.execute(count_stmt).scalar()
    
    # 使用JOIN查询关联project_info和token_info表
    items = db.query(
        ApiInfo,
        ProjectInfo.project_name,
        ProjectInfo.project_address,
        TokenInfo.name.label('token_name'),
        TokenInfo.token
    ).outerjoin(
        ProjectInfo, ApiInfo.project_id == ProjectInfo.project_id
    ).outerjoin(
        TokenInfo, ApiInfo.token_id == TokenInfo.token_id
    ).filter(*data.filter_params()).offset(offset).limit(data.page_size).all()
    
    # 将查询结果转换为ApiInfoInfo对象列表
    result_list = []
    for item in items:
        api_info = item[0]
        result_dict = ApiInfoInfo(
            api_id=api_info.api_id,
            api_name=api_info.api_name,
            method_type=api_info.method_type,
            method_url=api_info.method_url,
            project_id=api_info.project_id,
            token_id=api_info.token_id,
            request_header=api_info.request_header,
            params_path=api_info.params_path,
            description=api_info.description,
            remark=api_info.remark,
            creator=api_info.creator,
            create_time=api_info.create_time,
            update_time=api_info.update_time,
            project_name=item[1],
            project_address=item[2],
            token_name=item[3],
            token=item[4]
        )
        result_list.append(result_dict)
    
    return result_list, total



async def get_api_info_list_by_project_id(
    db: Session, 
    project_id: int
) -> List[ApiInfo]:
    """根据项目ID获取接口信息列表（不分页）
    
    Args:
        db: 数据库会话
        project_id: 项目ID
        
    Returns:
        List[ApiInfo]: API信息列表
    """
    # 查询所有符合条件的数据
    items = db.query(ApiInfo).filter(
        ApiInfo.project_id == project_id
    ).all()
    
    return items


async def create_api_info(db: Session, data: dict) -> ApiInfo:
    """创建接口信息
    
    Args:
        db: 数据库会话
        data: 接口信息数据字典
        
    Returns:
        ApiInfo: 创建的接口信息对象
    """
    # 自动设置审计字段（创建时间、更新时间）
    data = set_audit_fields_for_create(data)
    db_obj = ApiInfo(**data)
    db.add(db_obj)
    db.commit()
    db.refresh(db_obj)
    return db_obj


async def update_api_info(db: Session, api_id: int, data: dict) -> Optional[ApiInfo]:
    """更新接口信息
    
    Args:
        db: 数据库会话
        api_id: 接口ID
        data: 更新的字段数据字典
        
    Returns:
        Optional[ApiInfo]: 更新后的接口信息对象，如果不存在则返回None
    """
    db_obj = db.query(ApiInfo).filter(ApiInfo.api_id == api_id).first()
    if db_obj:
        # 自动设置更新时间
        data = set_audit_fields_for_update(data)
        for key, value in data.items():
            setattr(db_obj, key, value)
        db.commit()
        db.refresh(db_obj)
    return db_obj


async def delete_api_info(db: Session, api_id: int) -> Optional[ApiInfo]:
    """删除接口信息
    
    Args:
        db: 数据库会话
        api_id: 接口ID
        
    Returns:
        Optional[ApiInfo]: 被删除的接口信息对象，如果不存在则返回None
    """
    db_obj = db.query(ApiInfo).filter(ApiInfo.api_id == api_id).first()
    if db_obj:
        db.delete(db_obj)
        db.commit()
    return db_obj
