"""
API执行CRUD操作
Generated by scaffold script
"""
from sqlalchemy.orm import Session, joinedload
from models.api_instance_model import ApiInstance
from models.api_info_model import ApiInfo
from models.token_info_model import TokenInfo
from models.project_info_model import ProjectInfo
from typing import Optional, List, Dict, Any
import json


def get_api_execution_context(db: Session, instance_id: int) -> Optional[Dict[str, Any]]:
    """获取执行所需的完整上下文信息（关联查询）- 同步版本"""
    instance = db.query(ApiInstance).filter(ApiInstance.instance_id == instance_id).first()
    if not instance:
        return None
    
    api_info = db.query(ApiInfo).filter(ApiInfo.api_id == instance.api_id).first()
    if not api_info:
        return None
        
    project_info = db.query(ProjectInfo).filter(ProjectInfo.project_id == api_info.project_id).first()
    
    token_info = None
    if api_info.token_id:
        token_info = db.query(TokenInfo).filter(TokenInfo.token_id == api_info.token_id).first()
        
    return {
        "instance": instance,
        "api_info": api_info,
        "project_info": project_info,
        "token_info": token_info
    }


def get_existing_instance_ids(db: Session, instance_ids: List[int]) -> set:
    """返回在 api_instance 表中真实存在的 instance_id 集合

    用于在写入 api_result 前过滤掉不存在的实例，避免触发
    外键约束 fk_result_instance (api_result.instance_id -> api_instance.instance_id) 失败。
    """
    if not instance_ids:
        return set()
    rows = db.query(ApiInstance.instance_id).filter(
        ApiInstance.instance_id.in_(instance_ids)
    ).all()
    return {row[0] for row in rows}


async def get_instances_by_api_id(db: Session, api_id: int) -> List[ApiInstance]:
    """根据API ID获取所有实例"""
    return db.query(ApiInstance).filter(ApiInstance.api_id == api_id).all()


async def get_instances_by_project_id(db: Session, project_id: int) -> List[ApiInstance]:
    """根据项目ID获取该项目下所有API的所有实例"""
    # 先查出项目下所有的api_id
    api_ids = db.query(ApiInfo.api_id).filter(ApiInfo.project_id == project_id).all()
    api_id_list = [aid[0] for aid in api_ids]
    
    if not api_id_list:
        return []
        
    return db.query(ApiInstance).filter(ApiInstance.api_id.in_(api_id_list)).all()


def update_api_instance_exec_count(db: Session, instance_id: int) -> bool:
    """更新API实例的执行次数 - 同步版本"""
    instance = db.query(ApiInstance).filter(ApiInstance.instance_id == instance_id).first()
    if instance:
        instance.exec_count = (instance.exec_count or 0) + 1
        db.commit()
        return True
    return False
