"""
接口模板CRUD操作
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from sqlalchemy import and_, func,select
from models.api_template_model import ApiTemplate
from models.api_info_model import ApiInfo
from models.project_info_model import ProjectInfo
from typing import List, Optional, Tuple
from schemas.api_template_schemas import ApiTemplateList


async def get_api_template_by_id(db: Session, template_id: int) -> Optional[ApiTemplate]:
    """根据ID获取接口模板"""
    return db.query(ApiTemplate).filter(ApiTemplate.template_id == template_id).first()


async def get_api_template_by_unique_fields(
    db: Session, 
    api_id: int, 
    field_name: str
) -> Optional[ApiTemplate]:
    """根据唯一字段组合获取接口模板
    
    Args:
        db: 数据库会话
        api_id: API ID
        field_name: 字段名称
        
    Returns:
        Optional[ApiTemplate]: 如果存在则返回API模板，否则返回None
    """
    return db.query(ApiTemplate).filter(
        and_(
            ApiTemplate.api_id == api_id,
            ApiTemplate.field_name == field_name
        )
    ).first()


async def get_api_template_list(
    db: Session, 
    data: ApiTemplateList
) -> Tuple[List[dict], int]:
    """获取接口模板分页列表（包含API名称和项目信息）
    
    Returns:
        Tuple[List[dict], int]: (数据列表, 总记录数)
    """
    """计算偏移量"""
    offset = (data.page_num - 1) * data.page_size
    
    """查询总数"""
    count_stmt = select(func.count()).select_from(ApiTemplate).join(
        ApiInfo, ApiTemplate.api_id == ApiInfo.api_id
    ).outerjoin(
        ProjectInfo, ApiInfo.project_id == ProjectInfo.project_id
    ).where(*data.filter_params())
    total = db.execute(count_stmt).scalar()
    
    """使用JOIN查询关联api_info和project_info表"""
    items = db.query(
        ApiTemplate,
        ApiInfo.api_name,
        ApiInfo.project_id,
        ProjectInfo.project_name
    ).join(
        ApiInfo, ApiTemplate.api_id == ApiInfo.api_id
    ).outerjoin(
        ProjectInfo, ApiInfo.project_id == ProjectInfo.project_id
    ).filter(*data.filter_params()).order_by(ApiTemplate.template_id.desc(),ApiInfo.api_id.desc()).offset(offset).limit(data.page_size).all()
    
    """将查询结果转换为字典列表"""
    result_list = []
    for item in items:
        template = item[0]
        result_dict = {
            'template_id': template.template_id,
            'field_name': template.field_name,
            'field_type': template.field_type,
            'field_size': template.field_size,
            'default_value': template.default_value,
            'is_required': template.is_required,
            'api_id': template.api_id,
            'remark': template.remark,
            'creator': template.creator,
            'create_time': template.create_time,
            'update_time': template.update_time,
            'api_name': item[1],
            'project_id': item[2],
            'project_name': item[3]
        }
        result_list.append(result_dict)
    
    return result_list, total


async def create_api_template(db: Session, data: dict) -> ApiTemplate:
    """创建接口模板"""
    db_obj = ApiTemplate(**data)
    db.add(db_obj)
    db.commit()
    db.refresh(db_obj)
    return db_obj


async def update_api_template(db: Session, template_id: int, data: dict) -> Optional[ApiTemplate]:
    """更新接口模板"""
    db_obj = db.query(ApiTemplate).filter(ApiTemplate.template_id == template_id).first()
    if db_obj:
        for key, value in data.items():
            setattr(db_obj, key, value)
        db.commit()
        db.refresh(db_obj)
    return db_obj


async def batch_create_api_templates(db: Session, data_list: List[dict]) -> int:
    """批量创建接口模板（高性能版）"""
    if not data_list:
        return 0
    
    """使用 bulk_insert_mappings 跳过 ORM 实例化过程，直接生成 INSERT 语句"""
    db.bulk_insert_mappings(ApiTemplate, data_list)
    db.commit()
    return len(data_list)


async def get_existing_template_fields(db: Session, api_ids: List[int]) -> set:
    """获取指定API ID列表下已存在的模板字段名集合（用于内存去重）"""
    if not api_ids:
        return set()
    
    """查询已存在的 (api_id, field_name) 组合"""
    results = db.query(ApiTemplate.api_id, ApiTemplate.field_name).filter(
        ApiTemplate.api_id.in_(api_ids)
    ).all()
    
    return {f"{r[0]}_{r[1]}" for r in results}


async def delete_api_template(db: Session, template_id: int) -> Optional[ApiTemplate]:
    """删除接口模板"""
    db_obj = db.query(ApiTemplate).filter(ApiTemplate.template_id == template_id).first()
    if db_obj:
        db.delete(db_obj)
        db.commit()
    return db_obj


async def delete_api_template_batch(db: Session, template_ids: List[int]) -> int:
    """批量删除接口参数模板"""
    if not template_ids:
        return 0
    deleted = db.query(ApiTemplate).filter(
        ApiTemplate.template_id.in_(template_ids)
    ).delete(synchronize_session=False)
    db.commit()
    return deleted


async def delete_api_template_by_api_id(db: Session, api_id: int):
    """根据API ID批量删除模板"""
    db.query(ApiTemplate).filter(ApiTemplate.api_id == api_id).delete(synchronize_session=False)
    db.commit()
