"""
字典信息CRUD操作
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from sqlalchemy import and_, func
from models.dict_info_model import DictInfo
from typing import List, Optional, Tuple


async def get_dict_info_by_id(db: Session, dict_id: int) -> Optional[DictInfo]:
    """根据ID获取字典信息"""
    return db.query(DictInfo).filter(DictInfo.dict_id == dict_id).first()


async def get_dict_info_by_unique_fields(
    db: Session, 
    dict_name: str, 
    type: int
) -> Optional[DictInfo]:
    """根据唯一字段组合获取字典信息
    
    Args:
        db: 数据库会话
        dict_name: 字典名称
        type: 类型
        
    Returns:
        Optional[DictInfo]: 如果存在则返回字典信息，否则返回None
    """
    return db.query(DictInfo).filter(
        and_(
            DictInfo.dict_name == dict_name,
            DictInfo.type == type
        )
    ).first()


async def get_dict_info_list(
    db: Session, 
    page_num: int = 1, 
    page_size: int = 10
) -> Tuple[List[DictInfo], int]:
    """获取字典信息分页列表
    
    Returns:
        Tuple[List[DictInfo], int]: (数据列表, 总记录数)
    """
    # 计算偏移量
    offset = (page_num - 1) * page_size
    
    # 查询总数
    total = db.query(func.count(DictInfo.dict_id)).scalar()
    
    # 查询分页数据
    items = db.query(DictInfo).offset(offset).limit(page_size).all()
    
    return items, total


async def create_dict_info(db: Session, data: dict) -> DictInfo:
    """创建字典信息"""
    db_obj = DictInfo(**data)
    db.add(db_obj)
    db.commit()
    db.refresh(db_obj)
    return db_obj


async def update_dict_info(db: Session, dict_id: int, data: dict) -> Optional[DictInfo]:
    """更新字典信息"""
    db_obj = db.query(DictInfo).filter(DictInfo.dict_id == dict_id).first()
    if db_obj:
        for key, value in data.items():
            setattr(db_obj, key, value)
        db.commit()
        db.refresh(db_obj)
    return db_obj


async def delete_dict_info(db: Session, dict_id: int) -> Optional[DictInfo]:
    """删除字典信息"""
    db_obj = db.query(DictInfo).filter(DictInfo.dict_id == dict_id).first()
    if db_obj:
        db.delete(db_obj)
        db.commit()
    return db_obj
