"""
元素模板CRUD操作
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from sqlalchemy import and_, func
from models.element_template_model import ElementTemplate
from typing import List, Optional, Tuple


async def get_element_template_by_id(db: Session, element_id: int) -> Optional[ElementTemplate]:
    """根据ID获取元素模板"""
    return db.query(ElementTemplate).filter(ElementTemplate.element_id == element_id).first()


async def get_element_template_by_unique_fields(
    db: Session, 
    element_name: str, 
    element_type: int,
    page_id: int
) -> Optional[ElementTemplate]:
    """根据唯一字段组合获取元素模板
    
    Args:
        db: 数据库会话
        element_name: 元素名称
        element_type: 元素类型
        
    Returns:
        Optional[ElementTemplate]: 如果存在则返回元素模板，否则返回None
    """
    return db.query(ElementTemplate).filter(
        and_(
            ElementTemplate.element_name == element_name,
            ElementTemplate.element_type == element_type,
            ElementTemplate.page_id == page_id
        )
    ).first()


async def get_element_template_list(
    db: Session, 
    page_num: int = 1, 
    page_size: int = 10
) -> Tuple[List[ElementTemplate], int]:
    """获取元素模板分页列表
    
    Returns:
        Tuple[List[ElementTemplate], int]: (数据列表, 总记录数)
    """
    # 计算偏移量
    offset = (page_num - 1) * page_size
    
    # 查询总数
    total = db.query(func.count(ElementTemplate.element_id)).scalar()
    
    # 查询分页数据
    items = db.query(ElementTemplate).offset(offset).limit(page_size).all()
    
    return items, total


async def create_element_template(db: Session, data: dict) -> ElementTemplate:
    """创建元素模板"""
    db_obj = ElementTemplate(**data)
    db.add(db_obj)
    db.commit()
    db.refresh(db_obj)
    return db_obj


async def update_element_template(db: Session, element_id: int, data: dict) -> Optional[ElementTemplate]:
    """更新元素模板"""
    db_obj = db.query(ElementTemplate).filter(ElementTemplate.element_id == element_id).first()
    if db_obj:
        for key, value in data.items():
            setattr(db_obj, key, value)
        db.commit()
        db.refresh(db_obj)
    return db_obj


async def delete_element_template(db: Session, element_id: int) -> Optional[ElementTemplate]:
    """删除元素模板"""
    db_obj = db.query(ElementTemplate).filter(ElementTemplate.element_id == element_id).first()
    if db_obj:
        db.delete(db_obj)
        db.commit()
    return db_obj
