"""
流程步骤CRUD操作
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from sqlalchemy import and_, func
from models.flow_step_model import FlowStep
from typing import List, Optional, Tuple


async def get_flow_step_by_id(db: Session, step_id: int) -> Optional[FlowStep]:
    """根据ID获取流程步骤"""
    return db.query(FlowStep).filter(FlowStep.step_id == step_id).first()


async def get_flow_step_by_unique_fields(
    db: Session, 
    api_id: int,
    instance_id: int
) -> Optional[FlowStep]:
    """根据唯一字段组合获取流程步骤
    
    Args:
        db: 数据库会话
        api_id: 接口ID
        instance_id: 实例ID
        
    Returns:
        Optional[FlowStep]: 如果存在则返回流程步骤，否则返回None
    """
    return db.query(FlowStep).filter(
        and_(
            FlowStep.api_id == api_id,
            FlowStep.instance_id == instance_id
        )
    ).first()


async def get_flow_step_list(
    db: Session, 
    page_num: int = 1, 
    page_size: int = 10
) -> Tuple[List[FlowStep], int]:
    """获取流程步骤分页列表
    
    Returns:
        Tuple[List[FlowStep], int]: (数据列表, 总记录数)
    """
    # 计算偏移量
    offset = (page_num - 1) * page_size
    
    # 查询总数
    total = db.query(func.count(FlowStep.step_id)).scalar()
    
    # 查询分页数据
    items = db.query(FlowStep).offset(offset).limit(page_size).all()
    
    return items, total


async def create_flow_step(db: Session, data: dict) -> FlowStep:
    """创建流程步骤"""
    db_obj = FlowStep(**data)
    db.add(db_obj)
    db.commit()
    db.refresh(db_obj)
    return db_obj


async def update_flow_step(db: Session, step_id: int, data: dict) -> Optional[FlowStep]:
    """更新流程步骤"""
    db_obj = db.query(FlowStep).filter(FlowStep.step_id == step_id).first()
    if db_obj:
        for key, value in data.items():
            setattr(db_obj, key, value)
        db.commit()
        db.refresh(db_obj)
    return db_obj


async def delete_flow_step(db: Session, step_id: int) -> Optional[FlowStep]:
    """删除流程步骤"""
    db_obj = db.query(FlowStep).filter(FlowStep.step_id == step_id).first()
    if db_obj:
        db.delete(db_obj)
        db.commit()
    return db_obj
