"""
流程步骤CRUD操作
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from sqlalchemy import and_, func, select
from models.flow_step_model import FlowStep
from models.api_info_model import ApiInfo
from models.api_instance_model import ApiInstance
from models.token_info_model import TokenInfo
from typing import List, Optional, Tuple
from schemas.flow_step_schemas import FlowStepList


async def get_flow_step_by_id(db: Session, step_id: int) -> Optional[dict]:
    """根据ID获取流程步骤（包含API和实例信息）"""
    item = db.query(
        FlowStep,
        ApiInfo.api_name,
        ApiInfo.method_url,
        ApiInstance.instance_name,
        TokenInfo.name.label("token_name")
    ).join(
        ApiInfo, FlowStep.api_id == ApiInfo.api_id
    ).outerjoin(
        ApiInstance, FlowStep.instance_id == ApiInstance.instance_id
    ).outerjoin(
        TokenInfo, FlowStep.token_id == TokenInfo.token_id
    ).filter(FlowStep.step_id == step_id).first()
    
    if not item:
        return None
    
    flow_step = item[0]
    return {
        'step_id': flow_step.step_id,
        'flow_id': flow_step.flow_id,
        'api_id': flow_step.api_id,
        'instance_id': flow_step.instance_id,
        'token_id': flow_step.token_id,
        'params': flow_step.params,
        'flow_type': flow_step.flow_type,
        'is_batch': flow_step.is_batch,
        'status': flow_step.status,
        'expect_result': flow_step.expect_result,
        'remark': flow_step.remark,
        'creator': flow_step.creator,
        'create_time': flow_step.create_time,
        'update_time': flow_step.update_time,
        'api_name': item[1],
        'method_url': item[2],
        'instance_name': item[3],
        'token_name': item[4]
    }


async def get_flow_step_by_unique_fields(
    db: Session, 
    api_id: int,
    instance_id: int
) -> Optional[FlowStep]:
    """根据唯一字段组合获取流程步骤
    
    Args:
        db: 数据库会话
        api_id: 接口ID
        instance_id: 实例ID
        
    Returns:
        Optional[FlowStep]: 如果存在则返回流程步骤，否则返回None
    """
    return db.query(FlowStep).filter(
        and_(
            FlowStep.api_id == api_id,
            FlowStep.instance_id == instance_id
        )
    ).first()


async def get_flow_step_list(
    db: Session, 
    filter_params: FlowStepList
) -> Tuple[List[dict], int]:
    """获取流程步骤分页列表（包含API和实例信息）
    
    Args:
        db: 数据库会话
        filter_params: 查询过滤参数
        
    Returns:
        Tuple[List[dict], int]: (数据列表, 总记录数)
    """
    """计算偏移量"""
    offset = (filter_params.page_num - 1) * filter_params.page_size
    
    """构建查询条件"""
    conditions = []
    if filter_params.flow_id is not None:
        conditions.append(FlowStep.flow_id == filter_params.flow_id)
    if filter_params.api_id is not None:
        conditions.append(FlowStep.api_id == filter_params.api_id)
    
    """查询总数"""
    count_stmt = select(func.count()).select_from(FlowStep)
    if conditions:
        count_stmt = count_stmt.where(and_(*conditions))
    total = db.execute(count_stmt).scalar()
    
    """查询分页数据（关联ApiInfo和ApiInstance）"""
    stmt = select(
        FlowStep,
        ApiInfo.api_name,
        ApiInfo.method_url,
        ApiInstance.instance_name,
        TokenInfo.name.label("token_name")
    ).join(
        ApiInfo, FlowStep.api_id == ApiInfo.api_id
    ).outerjoin(
        ApiInstance, FlowStep.instance_id == ApiInstance.instance_id
    ).outerjoin(
        TokenInfo, FlowStep.token_id == TokenInfo.token_id
    )
    
    if conditions:
        stmt = stmt.where(and_(*conditions))
    
    stmt = stmt.offset(offset).limit(filter_params.page_size).order_by(FlowStep.step_id.asc())
    
    result = db.execute(stmt).all()
    """转换为字典列表"""
    items = []
    for row in result:
        flow_step = row[0]
        items.append({
            'step_id': flow_step.step_id,
            'flow_id': flow_step.flow_id,
            'api_id': flow_step.api_id,
            'instance_id': flow_step.instance_id,
            'token_id': flow_step.token_id,
            'params': flow_step.params,
            'flow_type': flow_step.flow_type,
            'is_batch': flow_step.is_batch,
            'status': flow_step.status,
            'expect_result': flow_step.expect_result,
            'remark': flow_step.remark,
            'creator': flow_step.creator,
            'create_time': flow_step.create_time,
            'update_time': flow_step.update_time,
            'api_name': row[1],
            'method_url': row[2],
            'instance_name': row[3],
            'token_name': row[4]
        })
    
    return items, total


async def create_flow_step(db: Session, data: dict) -> FlowStep:
    """创建流程步骤"""
    db_obj = FlowStep(**data)
    db.add(db_obj)
    db.commit()
    db.refresh(db_obj)
    return db_obj


async def update_flow_step(db: Session, step_id: int, data: dict) -> Optional[FlowStep]:
    """更新流程步骤"""
    db_obj = db.query(FlowStep).filter(FlowStep.step_id == step_id).first()
    if db_obj:
        for key, value in data.items():
            setattr(db_obj, key, value)
        db.commit()
        db.refresh(db_obj)
    return db_obj


async def delete_flow_step(db: Session, step_id: int) -> Optional[FlowStep]:
    """删除流程步骤"""
    db_obj = db.query(FlowStep).filter(FlowStep.step_id == step_id).first()
    if db_obj:
        db.delete(db_obj)
        db.commit()
    return db_obj


async def get_flow_steps_by_flow_id(db: Session, flow_id: int) -> List[dict]:
    """根据流程ID获取所有步骤（包含API和实例信息）"""
    items = db.query(
        FlowStep,
        ApiInfo.api_name,
        ApiInfo.method_url,
        ApiInstance.instance_name,
        TokenInfo.name.label("token_name")
    ).join(
        ApiInfo, FlowStep.api_id == ApiInfo.api_id
    ).outerjoin(
        ApiInstance, FlowStep.instance_id == ApiInstance.instance_id
    ).outerjoin(
        TokenInfo, FlowStep.token_id == TokenInfo.token_id
    ).filter(FlowStep.flow_id == flow_id).order_by(FlowStep.step_id.asc()).all()
    
    result = []
    for row in items:
        flow_step = row[0]
        result.append({
            'step_id': flow_step.step_id,
            'flow_id': flow_step.flow_id,
            'api_id': flow_step.api_id,
            'instance_id': flow_step.instance_id,
            'token_id': flow_step.token_id,
            'params': flow_step.params,
            'flow_type': flow_step.flow_type,
            'is_batch': flow_step.is_batch,
            'status': flow_step.status,
            'expect_result': flow_step.expect_result,
            'remark': flow_step.remark,
            'creator': flow_step.creator,
            'create_time': flow_step.create_time,
            'update_time': flow_step.update_time,
            'api_name': row[1],
            'method_url': row[2],
            'instance_name': row[3],
            'token_name': row[4]
        })
    
    return result


async def delete_flow_steps_by_flow_id(db: Session, flow_id: int):
    """根据流程ID批量删除步骤"""
    db.query(FlowStep).filter(FlowStep.flow_id == flow_id).delete(synchronize_session=False)
    db.commit()


async def delete_flow_steps_by_api_id(db: Session, api_id: int):
    """根据 API ID 删除流程步骤。"""
    db.query(FlowStep).filter(FlowStep.api_id == api_id).delete(synchronize_session=False)
    db.commit()


async def delete_flow_steps_by_instance_ids(db: Session, instance_ids: list[int]):
    """根据 API 实例 ID 列表删除流程步骤。"""
    if not instance_ids:
        return
    db.query(FlowStep).filter(FlowStep.instance_id.in_(instance_ids)).delete(synchronize_session=False)
    db.commit()
