"""
流程信息CRUD操作
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from sqlalchemy import and_, func
from models.flow_info_model import FlowInfo
from typing import List, Optional, Tuple


async def get_flow_info_by_id(db: Session, flow_id: int) -> Optional[FlowInfo]:
    """根据ID获取流程信息"""
    return db.query(FlowInfo).filter(FlowInfo.flow_id == flow_id).first()


async def get_flow_info_by_unique_fields(
    db: Session, 
    flow_name: str, 
    project_id: int
) -> Optional[FlowInfo]:
    """根据唯一字段组合获取流程信息
    
    Args:
        db: 数据库会话
        flow_name: 流程名称
        project_id: 项目ID
        
    Returns:
        Optional[FlowInfo]: 如果存在则返回流程信息，否则返回None
    """
    return db.query(FlowInfo).filter(
        and_(
            FlowInfo.flow_name == flow_name,
            FlowInfo.project_id == project_id
        )
    ).first()


async def get_flow_info_list(
    db: Session, 
    page_num: int = 1, 
    page_size: int = 10
) -> Tuple[List[FlowInfo], int]:
    """获取流程信息分页列表
    
    Returns:
        Tuple[List[FlowInfo], int]: (数据列表, 总记录数)
    """
    # 计算偏移量
    offset = (page_num - 1) * page_size
    
    # 查询总数
    total = db.query(func.count(FlowInfo.flow_id)).scalar()
    
    # 查询分页数据
    items = db.query(FlowInfo).offset(offset).limit(page_size).all()
    
    return items, total


async def create_flow_info(db: Session, data: dict) -> FlowInfo:
    """创建流程信息"""
    db_obj = FlowInfo(**data)
    db.add(db_obj)
    db.commit()
    db.refresh(db_obj)
    return db_obj


async def update_flow_info(db: Session, flow_id: int, data: dict) -> Optional[FlowInfo]:
    """更新流程信息"""
    db_obj = db.query(FlowInfo).filter(FlowInfo.flow_id == flow_id).first()
    if db_obj:
        for key, value in data.items():
            setattr(db_obj, key, value)
        db.commit()
        db.refresh(db_obj)
    return db_obj


async def delete_flow_info(db: Session, flow_id: int) -> Optional[FlowInfo]:
    """删除流程信息"""
    db_obj = db.query(FlowInfo).filter(FlowInfo.flow_id == flow_id).first()
    if db_obj:
        db.delete(db_obj)
        db.commit()
    return db_obj
