"""
流程信息CRUD操作
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from sqlalchemy import and_, func, select
from models.flow_info_model import FlowInfo
from models.project_info_model import ProjectInfo
from typing import List, Optional, Tuple
from schemas.flow_info_schemas import FlowInfoList


async def get_flow_info_by_id(db: Session, flow_id: int) -> Optional[dict]:
    """根据ID获取流程信息（包含项目名称和地址）"""
    item = db.query(
        FlowInfo,
        ProjectInfo.project_name,
        ProjectInfo.project_address
    ).outerjoin(
        ProjectInfo, FlowInfo.project_id == ProjectInfo.project_id
    ).filter(FlowInfo.flow_id == flow_id).first()
    
    if not item:
        return None
    
    flow_info = item[0]
    return {
        'flow_id': flow_info.flow_id,
        'flow_name': flow_info.flow_name,
        'description': flow_info.description,
        'flow_type': flow_info.flow_type,
        'project_id': flow_info.project_id,
        'expect_result': flow_info.expect_result,
        'actual_result': flow_info.actual_result,
        'status': flow_info.status,
        'remark': flow_info.remark,
        'creator': flow_info.creator,
        'create_time': flow_info.create_time,
        'update_time': flow_info.update_time,
        'project_name': item[1],
        'project_address': item[2]
    }


async def get_flow_info_by_unique_fields(
    db: Session, 
    flow_name: str, 
    project_id: int
) -> Optional[FlowInfo]:
    """根据唯一字段组合获取流程信息
    
    Args:
        db: 数据库会话
        flow_name: 流程名称
        project_id: 项目ID
        
    Returns:
        Optional[FlowInfo]: 如果存在则返回流程信息，否则返回None
    """
    return db.query(FlowInfo).filter(
        and_(
            FlowInfo.flow_name == flow_name,
            FlowInfo.project_id == project_id
        )
    ).first()


async def get_flow_info_list(
    db: Session, 
    filter_params: FlowInfoList
) -> Tuple[List[dict], int]:
    """获取流程信息分页列表（包含项目名称和地址）
    
    Args:
        db: 数据库会话
        filter_params: 查询过滤参数
        
    Returns:
        Tuple[List[dict], int]: (数据列表, 总记录数)
    """
    """计算偏移量"""
    offset = (filter_params.page_num - 1) * filter_params.page_size
    
    """构建查询条件"""
    conditions = []
    if filter_params.flow_name:
        conditions.append(FlowInfo.flow_name.like(f"%{filter_params.flow_name}%"))
    if filter_params.project_id is not None:
        conditions.append(FlowInfo.project_id == filter_params.project_id)
    if filter_params.flow_type is not None:
        conditions.append(FlowInfo.flow_type == filter_params.flow_type)
    
    """查询总数"""
    count_stmt = select(func.count()).select_from(FlowInfo)
    if conditions:
        count_stmt = count_stmt.where(and_(*conditions))
    total = db.execute(count_stmt).scalar()
    
    """查询分页数据（关联ProjectInfo）"""
    stmt = select(
        FlowInfo,
        ProjectInfo.project_name,
        ProjectInfo.project_address
    ).outerjoin(
        ProjectInfo, FlowInfo.project_id == ProjectInfo.project_id
    )
    
    if conditions:
        stmt = stmt.where(and_(*conditions))
    
    stmt = stmt.offset(offset).limit(filter_params.page_size).order_by(FlowInfo.flow_id.desc())
    
    result = db.execute(stmt).all()
    
    """转换为字典列表"""
    items = []
    for row in result:
        flow_info = row[0]
        items.append({
            'flow_id': flow_info.flow_id,
            'flow_name': flow_info.flow_name,
            'description': flow_info.description,
            'flow_type': flow_info.flow_type,
            'project_id': flow_info.project_id,
            'expect_result': flow_info.expect_result,
            'actual_result': flow_info.actual_result,
            'status': flow_info.status,
            'remark': flow_info.remark,
            'creator': flow_info.creator,
            'create_time': flow_info.create_time,
            'update_time': flow_info.update_time,
            'project_name': row[1],
            'project_address': row[2]
        })
    
    return items, total


async def create_flow_info(db: Session, data: dict) -> FlowInfo:
    """创建流程信息"""
    db_obj = FlowInfo(**data)
    db.add(db_obj)
    db.commit()
    db.refresh(db_obj)
    return db_obj


async def update_flow_info(db: Session, flow_id: int, data: dict) -> Optional[FlowInfo]:
    """更新流程信息"""
    db_obj = db.query(FlowInfo).filter(FlowInfo.flow_id == flow_id).first()
    if db_obj:
        for key, value in data.items():
            setattr(db_obj, key, value)
        db.commit()
        db.refresh(db_obj)
    return db_obj


async def delete_flow_info(db: Session, flow_id: int) -> Optional[FlowInfo]:
    """删除流程信息"""
    db_obj = db.query(FlowInfo).filter(FlowInfo.flow_id == flow_id).first()
    if db_obj:
        db.delete(db_obj)
        db.commit()
    return db_obj
