"""
页面信息CRUD操作
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from sqlalchemy import and_, func
from models.page_info_model import PageInfo
from typing import List, Optional, Tuple


async def get_page_info_by_id(db: Session, page_id: int) -> Optional[PageInfo]:
    """根据ID获取页面信息"""
    return db.query(PageInfo).filter(PageInfo.page_id == page_id).first()


async def get_page_info_by_unique_fields(
    db: Session, 
    page_name: str, 
    project_id: int
) -> Optional[PageInfo]:
    """根据唯一字段组合获取页面信息
    
    Args:
        db: 数据库会话
        page_name: 页面名称
        project_id: 项目ID
        
    Returns:
        Optional[PageInfo]: 如果存在则返回页面信息，否则返回None
    """
    return db.query(PageInfo).filter(
        and_(
            PageInfo.page_name == page_name,
            PageInfo.project_id == project_id
        )
    ).first()


async def get_page_info_list(
    db: Session, 
    page_num: int = 1, 
    page_size: int = 10
) -> Tuple[List[PageInfo], int]:
    """获取页面信息分页列表
    
    Returns:
        Tuple[List[PageInfo], int]: (数据列表, 总记录数)
    """
    # 计算偏移量
    offset = (page_num - 1) * page_size
    
    # 查询总数
    total = db.query(func.count(PageInfo.page_id)).scalar()
    
    # 查询分页数据
    items = db.query(PageInfo).offset(offset).limit(page_size).all()
    
    return items, total


async def create_page_info(db: Session, data: dict) -> PageInfo:
    """创建页面信息"""
    db_obj = PageInfo(**data)
    db.add(db_obj)
    db.commit()
    db.refresh(db_obj)
    return db_obj


async def update_page_info(db: Session, page_id: int, data: dict) -> Optional[PageInfo]:
    """更新页面信息"""
    db_obj = db.query(PageInfo).filter(PageInfo.page_id == page_id).first()
    if db_obj:
        for key, value in data.items():
            setattr(db_obj, key, value)
        db.commit()
        db.refresh(db_obj)
    return db_obj


async def delete_page_info(db: Session, page_id: int) -> Optional[PageInfo]:
    """删除页面信息"""
    db_obj = db.query(PageInfo).filter(PageInfo.page_id == page_id).first()
    if db_obj:
        db.delete(db_obj)
        db.commit()
    return db_obj
