"""
页面实例CRUD操作
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from sqlalchemy import and_, func
from models.page_instance_model import PageInstance
from typing import List, Optional, Tuple


async def get_page_instance_by_id(db: Session, page_instance_id: int) -> Optional[PageInstance]:
    """根据ID获取页面实例"""
    return db.query(PageInstance).filter(PageInstance.page_instance_id == page_instance_id).first()


async def get_page_instance_by_unique_fields(
    db: Session, 
    instance_name: str, 
    page_id: int
) -> Optional[PageInstance]:
    """根据唯一字段组合获取页面实例
    
    Args:
        db: 数据库会话
        instance_name: 实例名称
        page_id: 页面ID
        
    Returns:
        Optional[PageInstance]: 如果存在则返回页面实例，否则返回None
    """
    return db.query(PageInstance).filter(
        and_(
            PageInstance.instance_name == instance_name,
            PageInstance.page_id == page_id
        )
    ).first()


async def get_page_instance_list(
    db: Session, 
    page_num: int = 1, 
    page_size: int = 10
) -> Tuple[List[PageInstance], int]:
    """获取页面实例分页列表
    
    Returns:
        Tuple[List[PageInstance], int]: (数据列表, 总记录数)
    """
    # 计算偏移量
    offset = (page_num - 1) * page_size
    
    # 查询总数
    total = db.query(func.count(PageInstance.page_instance_id)).scalar()
    
    # 查询分页数据
    items = db.query(PageInstance).offset(offset).limit(page_size).all()
    
    return items, total


async def create_page_instance(db: Session, data: dict) -> PageInstance:
    """创建页面实例"""
    db_obj = PageInstance(**data)
    db.add(db_obj)
    db.commit()
    db.refresh(db_obj)
    return db_obj


async def update_page_instance(db: Session, page_instance_id: int, data: dict) -> Optional[PageInstance]:
    """更新页面实例"""
    db_obj = db.query(PageInstance).filter(PageInstance.page_instance_id == page_instance_id).first()
    if db_obj:
        for key, value in data.items():
            setattr(db_obj, key, value)
        db.commit()
        db.refresh(db_obj)
    return db_obj


async def delete_page_instance(db: Session, page_instance_id: int) -> Optional[PageInstance]:
    """删除页面实例"""
    db_obj = db.query(PageInstance).filter(PageInstance.page_instance_id == page_instance_id).first()
    if db_obj:
        db.delete(db_obj)
        db.commit()
    return db_obj
