"""
项目信息CRUD操作
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from sqlalchemy import and_, func, or_
from models.project_info_model import ProjectInfo
from typing import List, Optional, Tuple
from utils.data_paser import set_audit_fields_for_create, set_audit_fields_for_update


async def get_project_info_by_id(db: Session, project_id: int) -> Optional[ProjectInfo]:
    """根据ID获取项目信息"""
    return db.query(ProjectInfo).filter(ProjectInfo.project_id == project_id).first()


async def get_project_info_by_unique_fields(
    db: Session, 
    project_address: str
) -> Optional[ProjectInfo]:
    """根据唯一字段获取项目信息
    
    Args:
        db: 数据库会话
        project_address: 项目地址
        
    Returns:
        Optional[ProjectInfo]: 如果存在则返回项目信息，否则返回None
    """
    return db.query(ProjectInfo).filter(
        ProjectInfo.project_address == project_address
    ).first()


async def get_project_info_list(
    db: Session, 
    page_num: int = 1, 
    page_size: int = 10
) -> Tuple[List[ProjectInfo], int]:
    """获取项目信息分页列表
    
    Returns:
        Tuple[List[ProjectInfo], int]: (数据列表, 总记录数)
    """
    """计算偏移量"""
    offset = (page_num - 1) * page_size
    
    """查询总数"""
    total = db.query(func.count(ProjectInfo.project_id)).scalar()
    
    """查询分页数据"""
    items = db.query(ProjectInfo).offset(offset).limit(page_size).all()
    
    return items, total


async def get_project_info_select_options(db: Session) -> List[dict]:
    """获取轻量项目下拉列表。"""
    rows = db.query(
        ProjectInfo.project_id,
        ProjectInfo.project_name
    ).order_by(ProjectInfo.project_id.desc()).all()
    return [
        {
            "projectId": row.project_id,
            "projectName": row.project_name,
        }
        for row in rows
    ]


async def create_project_info(db: Session, data: dict) -> ProjectInfo:
    """创建项目信息"""
    """自动设置审计字段（创建时间、更新时间）"""
    data = set_audit_fields_for_create(data)
    db_obj = ProjectInfo(**data)
    db.add(db_obj)
    db.commit()
    db.refresh(db_obj)
    return db_obj


async def update_project_info(db: Session, project_id: int, data: dict) -> Optional[ProjectInfo]:
    """更新项目信息"""
    db_obj = db.query(ProjectInfo).filter(ProjectInfo.project_id == project_id).first()
    if db_obj:
        """自动设置更新时间"""
        data = set_audit_fields_for_update(data)
        for key, value in data.items():
            setattr(db_obj, key, value)
        db.commit()
        db.refresh(db_obj)
    return db_obj


async def delete_project_info(db: Session, project_id: int) -> Optional[ProjectInfo]:
    """删除项目信息"""
    db_obj = db.query(ProjectInfo).filter(ProjectInfo.project_id == project_id).first()
    if db_obj:
        db.delete(db_obj)
        db.commit()
    return db_obj
