"""
系统用户CRUD操作
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from sqlalchemy import and_, func
from models.sys_user_model import SysUser
from typing import List, Optional, Tuple
from utils.data_paser import set_audit_fields_for_create, set_audit_fields_for_update


async def get_sys_user_by_id(db: Session, user_id: int) -> Optional[SysUser]:
    """根据ID获取系统用户"""
    return db.query(SysUser).filter(SysUser.user_id == user_id).first()


async def get_sys_user_by_username(db: Session, username: str) -> Optional[SysUser]:
    """根据用户名获取系统用户（用于登录认证）

    Args:
        db: 数据库会话
        username: 用户名

    Returns:
        Optional[SysUser]: 如果存在则返回系统用户，否则返回None
    """
    return db.query(SysUser).filter(
        SysUser.username == username
    ).first()


async def get_sys_user_by_username(db: Session, username: str) -> Optional[SysUser]:
    """根据用户名获取系统用户
    
    Args:
        db: 数据库会话
        username: 用户名
        
    Returns:
        Optional[SysUser]: 如果存在则返回系统用户，否则返回None
    """
    return db.query(SysUser).filter(
        SysUser.username == username
    ).first()


async def get_sys_user_list(
    db: Session, 
    page_num: int = 1, 
    page_size: int = 10
) -> Tuple[List[SysUser], int]:
    """获取系统用户分页列表
    
    Returns:
        Tuple[List[SysUser], int]: (数据列表, 总记录数)
    """
    """计算偏移量"""
    offset = (page_num - 1) * page_size
    
    """查询总数"""
    total = db.query(func.count(SysUser.user_id)).scalar()
    
    """查询分页数据"""
    items = db.query(SysUser).offset(offset).limit(page_size).all()
    
    return items, total


async def create_sys_user(db: Session, data: dict) -> SysUser:
    """创建系统用户"""
    """自动设置审计字段（创建时间、更新时间）"""
    data = set_audit_fields_for_create(data)
    db_obj = SysUser(**data)
    db.add(db_obj)
    db.commit()
    db.refresh(db_obj)
    return db_obj


async def update_sys_user(db: Session, user_id: int, data: dict) -> Optional[SysUser]:
    """更新系统用户"""
    db_obj = db.query(SysUser).filter(SysUser.user_id == user_id).first()
    if db_obj:
        """自动设置更新时间"""
        data = set_audit_fields_for_update(data)
        for key, value in data.items():
            setattr(db_obj, key, value)
        db.commit()
        db.refresh(db_obj)
    return db_obj


async def delete_sys_user(db: Session, user_ids: list[int]) -> Optional[SysUser]:
    """删除系统用户"""
    db_obj = db.query(SysUser).filter(SysUser.user_id.in_(user_ids)).delete(synchronize_session=False)
    db.commit()
    return db_obj
