"""
Token信息CRUD操作
Generated by scaffold script
"""
from sqlalchemy.orm import Session
from sqlalchemy import and_, func,select
from models.token_info_model import TokenInfo
from models.project_info_model import ProjectInfo
from models.api_instance_model import ApiInstance
from models.api_info_model import ApiInfo
from models.page_instance_model import PageInstance
from models.page_info_model import PageInfo
from typing import List, Optional, Tuple
from schemas.token_info_schemas import TokenInfoList



async def get_token_info_by_id(db: Session, token_id: int) -> Optional[TokenInfo]:
    """根据ID获取Token信息"""
    return db.query(TokenInfo).filter(TokenInfo.token_id == token_id).first()


async def get_token_info_by_unique_fields(
    db: Session, 
    project_id: int, 
    name: str
) -> Optional[TokenInfo]:
    """根据唯一字段组合获取Token信息
    
    Args:
        db: 数据库会话
        project_id: 项目ID
        name: Token名称
        
    Returns:
        Optional[TokenInfo]: 如果存在则返回Token信息，否则返回None
    """
    return db.query(TokenInfo).filter(
        and_(
            TokenInfo.project_id == project_id,
            TokenInfo.name == name
        )
    ).first()


async def get_token_info_list(
    db: Session, 
    filter: TokenInfoList
) -> Tuple[List[dict], int]:
    """获取Token信息分页列表（包含项目名称、项目地址）
    
    Args:
        db: 数据库会话
        page_num: int = filter.page_num,
        page_size: int = filter.page_size
        
    Returns:
        Tuple[List[dict], int]: (数据列表, 总记录数)
    """
    """计算偏移量"""
    offset = (filter.page_num - 1) * filter.page_size
    
    """查询总数"""
    count_stmt = select(func.count()).select_from(TokenInfo).outerjoin(
        ProjectInfo, TokenInfo.project_id == ProjectInfo.project_id
    ).where(*filter.filter_params())
    total = db.execute(count_stmt).scalar()
    
    """使用JOIN查询关联project_info表，并按来源补充API/页面关联信息"""
    items = db.query(
        TokenInfo,
        ProjectInfo.project_name,
        ProjectInfo.project_address,
        ApiInstance.api_id,
        ApiInfo.api_name,
        ApiInstance.instance_name.label("api_instance_name"),
        PageInstance.page_id,
        PageInfo.page_name,
        PageInstance.instance_name.label("page_instance_name")
    ).outerjoin(
        ProjectInfo, TokenInfo.project_id == ProjectInfo.project_id
    ).outerjoin(
        ApiInstance,
        and_(TokenInfo.token_type == 1, TokenInfo.instance_id == ApiInstance.instance_id)
    ).outerjoin(
        ApiInfo, ApiInstance.api_id == ApiInfo.api_id
    ).outerjoin(
        PageInstance,
        and_(TokenInfo.token_type == 2, TokenInfo.instance_id == PageInstance.page_instance_id)
    ).outerjoin(
        PageInfo, PageInstance.page_id == PageInfo.page_id
    ).filter(*filter.filter_params()).offset(offset).limit(filter.page_size).all()
    
    """将查询结果转换为字典列表"""
    result_list = []
    for item in items:
        token_info = item[0]
        result_dict = {
            'token_id': token_info.token_id,
            'name': token_info.name,
            'type': token_info.type,
            'token_type': token_info.token_type,
            'project_id': token_info.project_id,
            'instance_id': token_info.instance_id,
            'status': token_info.status,
            'token': token_info.token,
            'remark': token_info.remark,
            'creator': token_info.creator,
            'create_time': token_info.create_time,
            'update_time': token_info.update_time,
            'project_name': item[1],
            'project_address': item[2],
            'api_id': item[3],
            'api_name': item[4],
            'api_instance_name': item[5],
            'page_id': item[6],
            'page_name': item[7],
            'page_instance_name': item[8],
        }
        result_list.append(result_dict)
    
    return result_list, total


async def get_token_info_options(
    db: Session,
    project_id: Optional[int],
    token_type: int,
    name: Optional[str] = None
) -> List[dict]:
    """获取Token下拉框列表，来源token_type必填。"""
    query = db.query(TokenInfo).filter(TokenInfo.token_type == token_type)
    if project_id is not None:
        query = query.filter(TokenInfo.project_id == project_id)
    if name:
        query = query.filter(TokenInfo.name.contains(name))

    rows = query.order_by(TokenInfo.token_id.desc()).all()
    return [
        {
            "token_id": row.token_id,
            "name": row.name,
            "type": row.type,
            "token_type": row.token_type,
            "project_id": row.project_id,
            "instance_id": row.instance_id,
            "token": row.token,
        }
        for row in rows
    ]


async def get_token_info_select_options(
    db: Session,
    project_id: Optional[int] = None,
    token_type: Optional[int] = None,
    name: Optional[str] = None
) -> List[dict]:
    """获取轻量Token下拉列表，不返回分页信息和token值。"""
    query = db.query(
        TokenInfo.token_id,
        TokenInfo.name,
        TokenInfo.token_type
    )
    if project_id is not None:
        query = query.filter(TokenInfo.project_id == project_id)
    if token_type is not None:
        query = query.filter(TokenInfo.token_type == token_type)
    if name:
        query = query.filter(TokenInfo.name.contains(name))

    rows = query.order_by(TokenInfo.token_id.desc()).all()
    return [
        {
            "tokenId": row.token_id,
            "tokenName": row.name,
            "tokenType": row.token_type,
        }
        for row in rows
    ]


async def create_token_info(db: Session, data: dict) -> TokenInfo:
    """创建Token信息"""
    db_obj = TokenInfo(**data)
    db.add(db_obj)
    db.commit()
    db.refresh(db_obj)
    return db_obj


async def update_token_info(db: Session, token_id: int, data: dict) -> Optional[TokenInfo]:
    """更新Token信息"""
    db_obj = db.query(TokenInfo).filter(TokenInfo.token_id == token_id).first()
    if db_obj:
        for key, value in data.items():
            setattr(db_obj, key, value)
        db.commit()
        db.refresh(db_obj)
    return db_obj


async def delete_token_info(db: Session, token_id: int) -> Optional[TokenInfo]:
    """删除Token信息"""
    db_obj = db.query(TokenInfo).filter(TokenInfo.token_id == token_id).first()
    if db_obj:
        db.delete(db_obj)
        db.commit()
    return db_obj


async def delete_token_info_batch(db: Session, token_ids: List[int]) -> int:
    """批量删除Token信息"""
    if not token_ids:
        return 0
    count = db.query(TokenInfo).filter(
        TokenInfo.token_id.in_(token_ids)
    ).delete(synchronize_session=False)
    if count:
        db.commit()
    return count
